[genshin]
resource_path = "C:/Users/FlourishingWorld/Desktop/GI/GameDataConfigTable"
gacha_history_server = "http://172.16.2.155:9004"

[logger]
level = "DEBUG"
method = "CONSOLE"
track_line = true

[air]
addr = "air-service"
port = 8086
service_name = "game-genshin-app"

[light]
port = 10006

[database]
url = "mongodb://mongodb-service:27017"

[mq]
nats_url = "nats://nats-service:4222,nats://nats-service:4223,nats://nats-service:4224"
