package constant

type FightProperty struct {
	FIGHT_PROP_NONE                             uint16
	FIGHT_PROP_BASE_HP                          uint16
	FIGHT_PROP_HP                               uint16
	FIGHT_PROP_HP_PERCENT                       uint16
	FIGHT_PROP_BASE_ATTACK                      uint16
	FIGHT_PROP_ATTACK                           uint16
	FIGHT_PROP_ATTACK_PERCENT                   uint16
	FIGHT_PROP_BASE_DEFENSE                     uint16
	FIGHT_PROP_DEFENSE                          uint16
	FIGHT_PROP_DEFENSE_PERCENT                  uint16
	FIGHT_PROP_BASE_SPEED                       uint16
	FIGHT_PROP_SPEED_PERCENT                    uint16
	FIGHT_PROP_HP_MP_PERCENT                    uint16
	FIGHT_PROP_ATTACK_MP_PERCENT                uint16
	FIGHT_PROP_CRITICAL                         uint16
	FIGHT_PROP_ANTI_CRITICAL                    uint16
	FIGHT_PROP_CRITICAL_HURT                    uint16
	FIGHT_PROP_CHARGE_EFFICIENCY                uint16
	FIGHT_PROP_ADD_HURT                         uint16
	FIGHT_PROP_SUB_HURT                         uint16
	FIGHT_PROP_HEAL_ADD                         uint16
	FIGHT_PROP_HEALED_ADD                       uint16
	FIGHT_PROP_ELEMENT_MASTERY                  uint16
	FIGHT_PROP_PHYSICAL_SUB_HURT                uint16
	FIGHT_PROP_PHYSICAL_ADD_HURT                uint16
	FIGHT_PROP_DEFENCE_IGNORE_RATIO             uint16
	FIGHT_PROP_DEFENCE_IGNORE_DELTA             uint16
	FIGHT_PROP_FIRE_ADD_HURT                    uint16
	FIGHT_PROP_ELEC_ADD_HURT                    uint16
	FIGHT_PROP_WATER_ADD_HURT                   uint16
	FIGHT_PROP_GRASS_ADD_HURT                   uint16
	FIGHT_PROP_WIND_ADD_HURT                    uint16
	FIGHT_PROP_ROCK_ADD_HURT                    uint16
	FIGHT_PROP_ICE_ADD_HURT                     uint16
	FIGHT_PROP_HIT_HEAD_ADD_HURT                uint16
	FIGHT_PROP_FIRE_SUB_HURT                    uint16
	FIGHT_PROP_ELEC_SUB_HURT                    uint16
	FIGHT_PROP_WATER_SUB_HURT                   uint16
	FIGHT_PROP_GRASS_SUB_HURT                   uint16
	FIGHT_PROP_WIND_SUB_HURT                    uint16
	FIGHT_PROP_ROCK_SUB_HURT                    uint16
	FIGHT_PROP_ICE_SUB_HURT                     uint16
	FIGHT_PROP_EFFECT_HIT                       uint16
	FIGHT_PROP_EFFECT_RESIST                    uint16
	FIGHT_PROP_FREEZE_RESIST                    uint16
	FIGHT_PROP_TORPOR_RESIST                    uint16
	FIGHT_PROP_DIZZY_RESIST                     uint16
	FIGHT_PROP_FREEZE_SHORTEN                   uint16
	FIGHT_PROP_TORPOR_SHORTEN                   uint16
	FIGHT_PROP_DIZZY_SHORTEN                    uint16
	FIGHT_PROP_MAX_FIRE_ENERGY                  uint16
	FIGHT_PROP_MAX_ELEC_ENERGY                  uint16
	FIGHT_PROP_MAX_WATER_ENERGY                 uint16
	FIGHT_PROP_MAX_GRASS_ENERGY                 uint16
	FIGHT_PROP_MAX_WIND_ENERGY                  uint16
	FIGHT_PROP_MAX_ICE_ENERGY                   uint16
	FIGHT_PROP_MAX_ROCK_ENERGY                  uint16
	FIGHT_PROP_SKILL_CD_MINUS_RATIO             uint16
	FIGHT_PROP_SHIELD_COST_MINUS_RATIO          uint16
	FIGHT_PROP_CUR_FIRE_ENERGY                  uint16
	FIGHT_PROP_CUR_ELEC_ENERGY                  uint16
	FIGHT_PROP_CUR_WATER_ENERGY                 uint16
	FIGHT_PROP_CUR_GRASS_ENERGY                 uint16
	FIGHT_PROP_CUR_WIND_ENERGY                  uint16
	FIGHT_PROP_CUR_ICE_ENERGY                   uint16
	FIGHT_PROP_CUR_ROCK_ENERGY                  uint16
	FIGHT_PROP_CUR_HP                           uint16
	FIGHT_PROP_MAX_HP                           uint16
	FIGHT_PROP_CUR_ATTACK                       uint16
	FIGHT_PROP_CUR_DEFENSE                      uint16
	FIGHT_PROP_CUR_SPEED                        uint16
	FIGHT_PROP_NONEXTRA_ATTACK                  uint16
	FIGHT_PROP_NONEXTRA_DEFENSE                 uint16
	FIGHT_PROP_NONEXTRA_CRITICAL                uint16
	FIGHT_PROP_NONEXTRA_ANTI_CRITICAL           uint16
	FIGHT_PROP_NONEXTRA_CRITICAL_HURT           uint16
	FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY       uint16
	FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY         uint16
	FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT       uint16
	FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT           uint16
	FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT           uint16
	FIGHT_PROP_NONEXTRA_WATER_ADD_HURT          uint16
	FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT          uint16
	FIGHT_PROP_NONEXTRA_WIND_ADD_HURT           uint16
	FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT           uint16
	FIGHT_PROP_NONEXTRA_ICE_ADD_HURT            uint16
	FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT           uint16
	FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT           uint16
	FIGHT_PROP_NONEXTRA_WATER_SUB_HURT          uint16
	FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT          uint16
	FIGHT_PROP_NONEXTRA_WIND_SUB_HURT           uint16
	FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT           uint16
	FIGHT_PROP_NONEXTRA_ICE_SUB_HURT            uint16
	FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO    uint16
	FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO uint16
	FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT       uint16
	STRING_MAP                                  map[string]uint16
}

func GetFightPropertyConst() (r *FightProperty) {
	r = new(FightProperty)

	r.FIGHT_PROP_NONE = 0
	r.FIGHT_PROP_BASE_HP = 1
	r.FIGHT_PROP_HP = 2
	r.FIGHT_PROP_HP_PERCENT = 3
	r.FIGHT_PROP_BASE_ATTACK = 4
	r.FIGHT_PROP_ATTACK = 5
	r.FIGHT_PROP_ATTACK_PERCENT = 6
	r.FIGHT_PROP_BASE_DEFENSE = 7
	r.FIGHT_PROP_DEFENSE = 8
	r.FIGHT_PROP_DEFENSE_PERCENT = 9
	r.FIGHT_PROP_BASE_SPEED = 10
	r.FIGHT_PROP_SPEED_PERCENT = 11
	r.FIGHT_PROP_HP_MP_PERCENT = 12
	r.FIGHT_PROP_ATTACK_MP_PERCENT = 13
	r.FIGHT_PROP_CRITICAL = 20
	r.FIGHT_PROP_ANTI_CRITICAL = 21
	r.FIGHT_PROP_CRITICAL_HURT = 22
	r.FIGHT_PROP_CHARGE_EFFICIENCY = 23
	r.FIGHT_PROP_ADD_HURT = 24
	r.FIGHT_PROP_SUB_HURT = 25
	r.FIGHT_PROP_HEAL_ADD = 26
	r.FIGHT_PROP_HEALED_ADD = 27
	r.FIGHT_PROP_ELEMENT_MASTERY = 28
	r.FIGHT_PROP_PHYSICAL_SUB_HURT = 29
	r.FIGHT_PROP_PHYSICAL_ADD_HURT = 30
	r.FIGHT_PROP_DEFENCE_IGNORE_RATIO = 31
	r.FIGHT_PROP_DEFENCE_IGNORE_DELTA = 32
	r.FIGHT_PROP_FIRE_ADD_HURT = 40
	r.FIGHT_PROP_ELEC_ADD_HURT = 41
	r.FIGHT_PROP_WATER_ADD_HURT = 42
	r.FIGHT_PROP_GRASS_ADD_HURT = 43
	r.FIGHT_PROP_WIND_ADD_HURT = 44
	r.FIGHT_PROP_ROCK_ADD_HURT = 45
	r.FIGHT_PROP_ICE_ADD_HURT = 46
	r.FIGHT_PROP_HIT_HEAD_ADD_HURT = 47
	r.FIGHT_PROP_FIRE_SUB_HURT = 50
	r.FIGHT_PROP_ELEC_SUB_HURT = 51
	r.FIGHT_PROP_WATER_SUB_HURT = 52
	r.FIGHT_PROP_GRASS_SUB_HURT = 53
	r.FIGHT_PROP_WIND_SUB_HURT = 54
	r.FIGHT_PROP_ROCK_SUB_HURT = 55
	r.FIGHT_PROP_ICE_SUB_HURT = 56
	r.FIGHT_PROP_EFFECT_HIT = 60
	r.FIGHT_PROP_EFFECT_RESIST = 61
	r.FIGHT_PROP_FREEZE_RESIST = 62
	r.FIGHT_PROP_TORPOR_RESIST = 63
	r.FIGHT_PROP_DIZZY_RESIST = 64
	r.FIGHT_PROP_FREEZE_SHORTEN = 65
	r.FIGHT_PROP_TORPOR_SHORTEN = 66
	r.FIGHT_PROP_DIZZY_SHORTEN = 67
	r.FIGHT_PROP_MAX_FIRE_ENERGY = 70
	r.FIGHT_PROP_MAX_ELEC_ENERGY = 71
	r.FIGHT_PROP_MAX_WATER_ENERGY = 72
	r.FIGHT_PROP_MAX_GRASS_ENERGY = 73
	r.FIGHT_PROP_MAX_WIND_ENERGY = 74
	r.FIGHT_PROP_MAX_ICE_ENERGY = 75
	r.FIGHT_PROP_MAX_ROCK_ENERGY = 76
	r.FIGHT_PROP_SKILL_CD_MINUS_RATIO = 80
	r.FIGHT_PROP_SHIELD_COST_MINUS_RATIO = 81
	r.FIGHT_PROP_CUR_FIRE_ENERGY = 1000
	r.FIGHT_PROP_CUR_ELEC_ENERGY = 1001
	r.FIGHT_PROP_CUR_WATER_ENERGY = 1002
	r.FIGHT_PROP_CUR_GRASS_ENERGY = 1003
	r.FIGHT_PROP_CUR_WIND_ENERGY = 1004
	r.FIGHT_PROP_CUR_ICE_ENERGY = 1005
	r.FIGHT_PROP_CUR_ROCK_ENERGY = 1006
	r.FIGHT_PROP_CUR_HP = 1010
	r.FIGHT_PROP_MAX_HP = 2000
	r.FIGHT_PROP_CUR_ATTACK = 2001
	r.FIGHT_PROP_CUR_DEFENSE = 2002
	r.FIGHT_PROP_CUR_SPEED = 2003
	r.FIGHT_PROP_NONEXTRA_ATTACK = 3000
	r.FIGHT_PROP_NONEXTRA_DEFENSE = 3001
	r.FIGHT_PROP_NONEXTRA_CRITICAL = 3002
	r.FIGHT_PROP_NONEXTRA_ANTI_CRITICAL = 3003
	r.FIGHT_PROP_NONEXTRA_CRITICAL_HURT = 3004
	r.FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY = 3005
	r.FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY = 3006
	r.FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT = 3007
	r.FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT = 3008
	r.FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT = 3009
	r.FIGHT_PROP_NONEXTRA_WATER_ADD_HURT = 3010
	r.FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT = 3011
	r.FIGHT_PROP_NONEXTRA_WIND_ADD_HURT = 3012
	r.FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT = 3013
	r.FIGHT_PROP_NONEXTRA_ICE_ADD_HURT = 3014
	r.FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT = 3015
	r.FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT = 3016
	r.FIGHT_PROP_NONEXTRA_WATER_SUB_HURT = 3017
	r.FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT = 3018
	r.FIGHT_PROP_NONEXTRA_WIND_SUB_HURT = 3019
	r.FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT = 3020
	r.FIGHT_PROP_NONEXTRA_ICE_SUB_HURT = 3021
	r.FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO = 3022
	r.FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO = 3023
	r.FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT = 3024

	r.STRING_MAP = make(map[string]uint16)

	r.STRING_MAP["FIGHT_PROP_NONE"] = 0
	r.STRING_MAP["FIGHT_PROP_BASE_HP"] = 1
	r.STRING_MAP["FIGHT_PROP_HP"] = 2
	r.STRING_MAP["FIGHT_PROP_HP_PERCENT"] = 3
	r.STRING_MAP["FIGHT_PROP_BASE_ATTACK"] = 4
	r.STRING_MAP["FIGHT_PROP_ATTACK"] = 5
	r.STRING_MAP["FIGHT_PROP_ATTACK_PERCENT"] = 6
	r.STRING_MAP["FIGHT_PROP_BASE_DEFENSE"] = 7
	r.STRING_MAP["FIGHT_PROP_DEFENSE"] = 8
	r.STRING_MAP["FIGHT_PROP_DEFENSE_PERCENT"] = 9
	r.STRING_MAP["FIGHT_PROP_BASE_SPEED"] = 10
	r.STRING_MAP["FIGHT_PROP_SPEED_PERCENT"] = 11
	r.STRING_MAP["FIGHT_PROP_HP_MP_PERCENT"] = 12
	r.STRING_MAP["FIGHT_PROP_ATTACK_MP_PERCENT"] = 13
	r.STRING_MAP["FIGHT_PROP_CRITICAL"] = 20
	r.STRING_MAP["FIGHT_PROP_ANTI_CRITICAL"] = 21
	r.STRING_MAP["FIGHT_PROP_CRITICAL_HURT"] = 22
	r.STRING_MAP["FIGHT_PROP_CHARGE_EFFICIENCY"] = 23
	r.STRING_MAP["FIGHT_PROP_ADD_HURT"] = 24
	r.STRING_MAP["FIGHT_PROP_SUB_HURT"] = 25
	r.STRING_MAP["FIGHT_PROP_HEAL_ADD"] = 26
	r.STRING_MAP["FIGHT_PROP_HEALED_ADD"] = 27
	r.STRING_MAP["FIGHT_PROP_ELEMENT_MASTERY"] = 28
	r.STRING_MAP["FIGHT_PROP_PHYSICAL_SUB_HURT"] = 29
	r.STRING_MAP["FIGHT_PROP_PHYSICAL_ADD_HURT"] = 30
	r.STRING_MAP["FIGHT_PROP_DEFENCE_IGNORE_RATIO"] = 31
	r.STRING_MAP["FIGHT_PROP_DEFENCE_IGNORE_DELTA"] = 32
	r.STRING_MAP["FIGHT_PROP_FIRE_ADD_HURT"] = 40
	r.STRING_MAP["FIGHT_PROP_ELEC_ADD_HURT"] = 41
	r.STRING_MAP["FIGHT_PROP_WATER_ADD_HURT"] = 42
	r.STRING_MAP["FIGHT_PROP_GRASS_ADD_HURT"] = 43
	r.STRING_MAP["FIGHT_PROP_WIND_ADD_HURT"] = 44
	r.STRING_MAP["FIGHT_PROP_ROCK_ADD_HURT"] = 45
	r.STRING_MAP["FIGHT_PROP_ICE_ADD_HURT"] = 46
	r.STRING_MAP["FIGHT_PROP_HIT_HEAD_ADD_HURT"] = 47
	r.STRING_MAP["FIGHT_PROP_FIRE_SUB_HURT"] = 50
	r.STRING_MAP["FIGHT_PROP_ELEC_SUB_HURT"] = 51
	r.STRING_MAP["FIGHT_PROP_WATER_SUB_HURT"] = 52
	r.STRING_MAP["FIGHT_PROP_GRASS_SUB_HURT"] = 53
	r.STRING_MAP["FIGHT_PROP_WIND_SUB_HURT"] = 54
	r.STRING_MAP["FIGHT_PROP_ROCK_SUB_HURT"] = 55
	r.STRING_MAP["FIGHT_PROP_ICE_SUB_HURT"] = 56
	r.STRING_MAP["FIGHT_PROP_EFFECT_HIT"] = 60
	r.STRING_MAP["FIGHT_PROP_EFFECT_RESIST"] = 61
	r.STRING_MAP["FIGHT_PROP_FREEZE_RESIST"] = 62
	r.STRING_MAP["FIGHT_PROP_TORPOR_RESIST"] = 63
	r.STRING_MAP["FIGHT_PROP_DIZZY_RESIST"] = 64
	r.STRING_MAP["FIGHT_PROP_FREEZE_SHORTEN"] = 65
	r.STRING_MAP["FIGHT_PROP_TORPOR_SHORTEN"] = 66
	r.STRING_MAP["FIGHT_PROP_DIZZY_SHORTEN"] = 67
	r.STRING_MAP["FIGHT_PROP_MAX_FIRE_ENERGY"] = 70
	r.STRING_MAP["FIGHT_PROP_MAX_ELEC_ENERGY"] = 71
	r.STRING_MAP["FIGHT_PROP_MAX_WATER_ENERGY"] = 72
	r.STRING_MAP["FIGHT_PROP_MAX_GRASS_ENERGY"] = 73
	r.STRING_MAP["FIGHT_PROP_MAX_WIND_ENERGY"] = 74
	r.STRING_MAP["FIGHT_PROP_MAX_ICE_ENERGY"] = 75
	r.STRING_MAP["FIGHT_PROP_MAX_ROCK_ENERGY"] = 76
	r.STRING_MAP["FIGHT_PROP_SKILL_CD_MINUS_RATIO"] = 80
	r.STRING_MAP["FIGHT_PROP_SHIELD_COST_MINUS_RATIO"] = 81
	r.STRING_MAP["FIGHT_PROP_CUR_FIRE_ENERGY"] = 1000
	r.STRING_MAP["FIGHT_PROP_CUR_ELEC_ENERGY"] = 1001
	r.STRING_MAP["FIGHT_PROP_CUR_WATER_ENERGY"] = 1002
	r.STRING_MAP["FIGHT_PROP_CUR_GRASS_ENERGY"] = 1003
	r.STRING_MAP["FIGHT_PROP_CUR_WIND_ENERGY"] = 1004
	r.STRING_MAP["FIGHT_PROP_CUR_ICE_ENERGY"] = 1005
	r.STRING_MAP["FIGHT_PROP_CUR_ROCK_ENERGY"] = 1006
	r.STRING_MAP["FIGHT_PROP_CUR_HP"] = 1010
	r.STRING_MAP["FIGHT_PROP_MAX_HP"] = 2000
	r.STRING_MAP["FIGHT_PROP_CUR_ATTACK"] = 2001
	r.STRING_MAP["FIGHT_PROP_CUR_DEFENSE"] = 2002
	r.STRING_MAP["FIGHT_PROP_CUR_SPEED"] = 2003
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ATTACK"] = 3000
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_DEFENSE"] = 3001
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_CRITICAL"] = 3002
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ANTI_CRITICAL"] = 3003
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_CRITICAL_HURT"] = 3004
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_CHARGE_EFFICIENCY"] = 3005
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ELEMENT_MASTERY"] = 3006
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_PHYSICAL_SUB_HURT"] = 3007
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_FIRE_ADD_HURT"] = 3008
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ELEC_ADD_HURT"] = 3009
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_WATER_ADD_HURT"] = 3010
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_GRASS_ADD_HURT"] = 3011
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_WIND_ADD_HURT"] = 3012
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ROCK_ADD_HURT"] = 3013
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ICE_ADD_HURT"] = 3014
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_FIRE_SUB_HURT"] = 3015
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ELEC_SUB_HURT"] = 3016
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_WATER_SUB_HURT"] = 3017
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_GRASS_SUB_HURT"] = 3018
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_WIND_SUB_HURT"] = 3019
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ROCK_SUB_HURT"] = 3020
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_ICE_SUB_HURT"] = 3021
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_SKILL_CD_MINUS_RATIO"] = 3022
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_SHIELD_COST_MINUS_RATIO"] = 3023
	r.STRING_MAP["FIGHT_PROP_NONEXTRA_PHYSICAL_ADD_HURT"] = 3024

	return r
}
