package constant

type MaterialType struct {
	MATERIAL_NONE                    uint16
	MATERIAL_FOOD                    uint16
	MATERIAL_QUEST                   uint16
	MATERIAL_EXCHANGE                uint16
	MATERIAL_CONSUME                 uint16
	MATERIAL_EXP_FRUIT               uint16
	MATERIAL_AVATAR                  uint16
	MATERIAL_ADSORBATE               uint16
	MATERIAL_CRICKET                 uint16
	MATERIAL_ELEM_CRYSTAL            uint16
	MATERIAL_WEAPON_EXP_STONE        uint16
	MATERIAL_CHEST                   uint16
	MATERIAL_RELIQUARY_MATERIAL      uint16
	MATERIAL_AVATAR_MATERIAL         uint16
	MATERIAL_NOTICE_ADD_HP           uint16
	MATERIAL_SEA_LAMP                uint16
	MATERIAL_SELECTABLE_CHEST        uint16
	MATERIAL_FLYCLOAK                uint16
	MATERIAL_NAMECARD                uint16
	MATERIAL_TALENT                  uint16
	MATERIAL_WIDGET                  uint16
	MATERIAL_CHEST_BATCH_USE         uint16
	MATERIAL_FAKE_ABSORBATE          uint16
	MATERIAL_CONSUME_BATCH_USE       uint16
	MATERIAL_WOOD                    uint16
	MATERIAL_FURNITURE_FORMULA       uint16
	MATERIAL_CHANNELLER_SLAB_BUFF    uint16
	MATERIAL_FURNITURE_SUITE_FORMULA uint16
	MATERIAL_COSTUME                 uint16
	STRING_MAP                       map[string]uint16
}

func GetMaterialTypeConst() (r *MaterialType) {
	r = new(MaterialType)

	r.MATERIAL_NONE = 0
	r.MATERIAL_FOOD = 1
	r.MATERIAL_QUEST = 2
	r.MATERIAL_EXCHANGE = 4
	r.MATERIAL_CONSUME = 5
	r.MATERIAL_EXP_FRUIT = 6
	r.MATERIAL_AVATAR = 7
	r.MATERIAL_ADSORBATE = 8
	r.MATERIAL_CRICKET = 9
	r.MATERIAL_ELEM_CRYSTAL = 10
	r.MATERIAL_WEAPON_EXP_STONE = 11
	r.MATERIAL_CHEST = 12
	r.MATERIAL_RELIQUARY_MATERIAL = 13
	r.MATERIAL_AVATAR_MATERIAL = 14
	r.MATERIAL_NOTICE_ADD_HP = 15
	r.MATERIAL_SEA_LAMP = 16
	r.MATERIAL_SELECTABLE_CHEST = 17
	r.MATERIAL_FLYCLOAK = 18
	r.MATERIAL_NAMECARD = 19
	r.MATERIAL_TALENT = 20
	r.MATERIAL_WIDGET = 21
	r.MATERIAL_CHEST_BATCH_USE = 22
	r.MATERIAL_FAKE_ABSORBATE = 23
	r.MATERIAL_CONSUME_BATCH_USE = 24
	r.MATERIAL_WOOD = 25
	r.MATERIAL_FURNITURE_FORMULA = 27
	r.MATERIAL_CHANNELLER_SLAB_BUFF = 28
	r.MATERIAL_FURNITURE_SUITE_FORMULA = 29
	r.MATERIAL_COSTUME = 30

	r.STRING_MAP = make(map[string]uint16)

	r.STRING_MAP["MATERIAL_NONE"] = 0
	r.STRING_MAP["MATERIAL_FOOD"] = 1
	r.STRING_MAP["MATERIAL_QUEST"] = 2
	r.STRING_MAP["MATERIAL_EXCHANGE"] = 4
	r.STRING_MAP["MATERIAL_CONSUME"] = 5
	r.STRING_MAP["MATERIAL_EXP_FRUIT"] = 6
	r.STRING_MAP["MATERIAL_AVATAR"] = 7
	r.STRING_MAP["MATERIAL_ADSORBATE"] = 8
	r.STRING_MAP["MATERIAL_CRICKET"] = 9
	r.STRING_MAP["MATERIAL_ELEM_CRYSTAL"] = 10
	r.STRING_MAP["MATERIAL_WEAPON_EXP_STONE"] = 11
	r.STRING_MAP["MATERIAL_CHEST"] = 12
	r.STRING_MAP["MATERIAL_RELIQUARY_MATERIAL"] = 13
	r.STRING_MAP["MATERIAL_AVATAR_MATERIAL"] = 14
	r.STRING_MAP["MATERIAL_NOTICE_ADD_HP"] = 15
	r.STRING_MAP["MATERIAL_SEA_LAMP"] = 16
	r.STRING_MAP["MATERIAL_SELECTABLE_CHEST"] = 17
	r.STRING_MAP["MATERIAL_FLYCLOAK"] = 18
	r.STRING_MAP["MATERIAL_NAMECARD"] = 19
	r.STRING_MAP["MATERIAL_TALENT"] = 20
	r.STRING_MAP["MATERIAL_WIDGET"] = 21
	r.STRING_MAP["MATERIAL_CHEST_BATCH_USE"] = 22
	r.STRING_MAP["MATERIAL_FAKE_ABSORBATE"] = 23
	r.STRING_MAP["MATERIAL_CONSUME_BATCH_USE"] = 24
	r.STRING_MAP["MATERIAL_WOOD"] = 25
	r.STRING_MAP["MATERIAL_FURNITURE_FORMULA"] = 27
	r.STRING_MAP["MATERIAL_CHANNELLER_SLAB_BUFF"] = 28
	r.STRING_MAP["MATERIAL_FURNITURE_SUITE_FORMULA"] = 29
	r.STRING_MAP["MATERIAL_COSTUME"] = 30

	return r
}
