// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: AbilityScalarType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AbilityScalarType int32

const (
	AbilityScalarType_UNKNOW  AbilityScalarType = 0
	AbilityScalarType_FLOAT   AbilityScalarType = 1
	AbilityScalarType_INT     AbilityScalarType = 2
	AbilityScalarType_BOOL    AbilityScalarType = 3
	AbilityScalarType_TRIGGER AbilityScalarType = 4
	AbilityScalarType_STRING  AbilityScalarType = 5
	AbilityScalarType_UINT    AbilityScalarType = 6
)

// Enum value maps for AbilityScalarType.
var (
	AbilityScalarType_name = map[int32]string{
		0: "UNKNOW",
		1: "FLOAT",
		2: "INT",
		3: "BOOL",
		4: "TRIGGER",
		5: "STRING",
		6: "UINT",
	}
	AbilityScalarType_value = map[string]int32{
		"UNKNOW":  0,
		"FLOAT":   1,
		"INT":     2,
		"BOOL":    3,
		"TRIGGER": 4,
		"STRING":  5,
		"UINT":    6,
	}
)

func (x AbilityScalarType) Enum() *AbilityScalarType {
	p := new(AbilityScalarType)
	*p = x
	return p
}

func (x AbilityScalarType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AbilityScalarType) Descriptor() protoreflect.EnumDescriptor {
	return file_AbilityScalarType_proto_enumTypes[0].Descriptor()
}

func (AbilityScalarType) Type() protoreflect.EnumType {
	return &file_AbilityScalarType_proto_enumTypes[0]
}

func (x AbilityScalarType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AbilityScalarType.Descriptor instead.
func (AbilityScalarType) EnumDescriptor() ([]byte, []int) {
	return file_AbilityScalarType_proto_rawDescGZIP(), []int{0}
}

var File_AbilityScalarType_proto protoreflect.FileDescriptor

var file_AbilityScalarType_proto_rawDesc = []byte{
	0x0a, 0x17, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x63, 0x61, 0x6c, 0x61, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2a, 0x60, 0x0a, 0x11, 0x41, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x63, 0x61, 0x6c, 0x61,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x4f, 0x41, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x49, 0x4e, 0x54, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x12,
	0x0b, 0x0a, 0x07, 0x54, 0x52, 0x49, 0x47, 0x47, 0x45, 0x52, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06,
	0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x49, 0x4e, 0x54,
	0x10, 0x06, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AbilityScalarType_proto_rawDescOnce sync.Once
	file_AbilityScalarType_proto_rawDescData = file_AbilityScalarType_proto_rawDesc
)

func file_AbilityScalarType_proto_rawDescGZIP() []byte {
	file_AbilityScalarType_proto_rawDescOnce.Do(func() {
		file_AbilityScalarType_proto_rawDescData = protoimpl.X.CompressGZIP(file_AbilityScalarType_proto_rawDescData)
	})
	return file_AbilityScalarType_proto_rawDescData
}

var file_AbilityScalarType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AbilityScalarType_proto_goTypes = []interface{}{
	(AbilityScalarType)(0), // 0: proto.AbilityScalarType
}
var file_AbilityScalarType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AbilityScalarType_proto_init() }
func file_AbilityScalarType_proto_init() {
	if File_AbilityScalarType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AbilityScalarType_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AbilityScalarType_proto_goTypes,
		DependencyIndexes: file_AbilityScalarType_proto_depIdxs,
		EnumInfos:         file_AbilityScalarType_proto_enumTypes,
	}.Build()
	File_AbilityScalarType_proto = out.File
	file_AbilityScalarType_proto_rawDesc = nil
	file_AbilityScalarType_proto_goTypes = nil
	file_AbilityScalarType_proto_depIdxs = nil
}
