// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: AchievementInfo.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AchievementInfo_AchievementInfoStatus int32

const (
	AchievementInfo_ACHIEVEMENT_INVALID     AchievementInfo_AchievementInfoStatus = 0
	AchievementInfo_ACHIEVEMENT_UNFINISHED  AchievementInfo_AchievementInfoStatus = 1
	AchievementInfo_ACHIEVEMENT_FINISHED    AchievementInfo_AchievementInfoStatus = 2
	AchievementInfo_ACHIEVEMENT_POINT_TAKEN AchievementInfo_AchievementInfoStatus = 3
)

// Enum value maps for AchievementInfo_AchievementInfoStatus.
var (
	AchievementInfo_AchievementInfoStatus_name = map[int32]string{
		0: "ACHIEVEMENT_INVALID",
		1: "ACHIEVEMENT_UNFINISHED",
		2: "ACHIEVEMENT_FINISHED",
		3: "ACHIEVEMENT_POINT_TAKEN",
	}
	AchievementInfo_AchievementInfoStatus_value = map[string]int32{
		"ACHIEVEMENT_INVALID":     0,
		"ACHIEVEMENT_UNFINISHED":  1,
		"ACHIEVEMENT_FINISHED":    2,
		"ACHIEVEMENT_POINT_TAKEN": 3,
	}
)

func (x AchievementInfo_AchievementInfoStatus) Enum() *AchievementInfo_AchievementInfoStatus {
	p := new(AchievementInfo_AchievementInfoStatus)
	*p = x
	return p
}

func (x AchievementInfo_AchievementInfoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AchievementInfo_AchievementInfoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_AchievementInfo_proto_enumTypes[0].Descriptor()
}

func (AchievementInfo_AchievementInfoStatus) Type() protoreflect.EnumType {
	return &file_AchievementInfo_proto_enumTypes[0]
}

func (x AchievementInfo_AchievementInfoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AchievementInfo_AchievementInfoStatus.Descriptor instead.
func (AchievementInfo_AchievementInfoStatus) EnumDescriptor() ([]byte, []int) {
	return file_AchievementInfo_proto_rawDescGZIP(), []int{0, 0}
}

type AchievementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32                                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status      AchievementInfo_AchievementInfoStatus `protobuf:"varint,2,opt,name=status,proto3,enum=proto.AchievementInfo_AchievementInfoStatus" json:"status,omitempty"`
	Current     uint32                                `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	Goal        uint32                                `protobuf:"varint,4,opt,name=goal,proto3" json:"goal,omitempty"`
	Achievedate uint32                                `protobuf:"varint,5,opt,name=achievedate,proto3" json:"achievedate,omitempty"`
}

func (x *AchievementInfo) Reset() {
	*x = AchievementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AchievementInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AchievementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AchievementInfo) ProtoMessage() {}

func (x *AchievementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_AchievementInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AchievementInfo.ProtoReflect.Descriptor instead.
func (*AchievementInfo) Descriptor() ([]byte, []int) {
	return file_AchievementInfo_proto_rawDescGZIP(), []int{0}
}

func (x *AchievementInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AchievementInfo) GetStatus() AchievementInfo_AchievementInfoStatus {
	if x != nil {
		return x.Status
	}
	return AchievementInfo_ACHIEVEMENT_INVALID
}

func (x *AchievementInfo) GetCurrent() uint32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *AchievementInfo) GetGoal() uint32 {
	if x != nil {
		return x.Goal
	}
	return 0
}

func (x *AchievementInfo) GetAchievedate() uint32 {
	if x != nil {
		return x.Achievedate
	}
	return 0
}

var File_AchievementInfo_proto protoreflect.FileDescriptor

var file_AchievementInfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x41, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbd,
	0x02, 0x0a, 0x0f, 0x41, 0x63, 0x68, 0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x68, 0x69, 0x65,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x41, 0x63, 0x68, 0x69, 0x65,
	0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x67, 0x6f, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x68, 0x69, 0x65, 0x76,
	0x65, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x63, 0x68,
	0x69, 0x65, 0x76, 0x65, 0x64, 0x61, 0x74, 0x65, 0x22, 0x83, 0x01, 0x0a, 0x15, 0x41, 0x63, 0x68,
	0x69, 0x65, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x17, 0x0a, 0x13, 0x41, 0x43, 0x48, 0x49, 0x45, 0x56, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x41,
	0x43, 0x48, 0x49, 0x45, 0x56, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x46, 0x49, 0x4e,
	0x49, 0x53, 0x48, 0x45, 0x44, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x43, 0x48, 0x49, 0x45,
	0x56, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x46, 0x49, 0x4e, 0x49, 0x53, 0x48, 0x45, 0x44, 0x10,
	0x02, 0x12, 0x1b, 0x0a, 0x17, 0x41, 0x43, 0x48, 0x49, 0x45, 0x56, 0x45, 0x4d, 0x45, 0x4e, 0x54,
	0x5f, 0x50, 0x4f, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x41, 0x4b, 0x45, 0x4e, 0x10, 0x03, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_AchievementInfo_proto_rawDescOnce sync.Once
	file_AchievementInfo_proto_rawDescData = file_AchievementInfo_proto_rawDesc
)

func file_AchievementInfo_proto_rawDescGZIP() []byte {
	file_AchievementInfo_proto_rawDescOnce.Do(func() {
		file_AchievementInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_AchievementInfo_proto_rawDescData)
	})
	return file_AchievementInfo_proto_rawDescData
}

var file_AchievementInfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AchievementInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AchievementInfo_proto_goTypes = []interface{}{
	(AchievementInfo_AchievementInfoStatus)(0), // 0: proto.AchievementInfo.AchievementInfoStatus
	(*AchievementInfo)(nil),                    // 1: proto.AchievementInfo
}
var file_AchievementInfo_proto_depIdxs = []int32{
	0, // 0: proto.AchievementInfo.status:type_name -> proto.AchievementInfo.AchievementInfoStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AchievementInfo_proto_init() }
func file_AchievementInfo_proto_init() {
	if File_AchievementInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AchievementInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AchievementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AchievementInfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AchievementInfo_proto_goTypes,
		DependencyIndexes: file_AchievementInfo_proto_depIdxs,
		EnumInfos:         file_AchievementInfo_proto_enumTypes,
		MessageInfos:      file_AchievementInfo_proto_msgTypes,
	}.Build()
	File_AchievementInfo_proto = out.File
	file_AchievementInfo_proto_rawDesc = nil
	file_AchievementInfo_proto_goTypes = nil
	file_AchievementInfo_proto_depIdxs = nil
}
