// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: AvatarChangeCostumeReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarChangeCostumeReq_CmdId int32

const (
	AvatarChangeCostumeReq_ENET_CHANNEL_ID  AvatarChangeCostumeReq_CmdId = 0
	AvatarChangeCostumeReq_NONE             AvatarChangeCostumeReq_CmdId = 0
	AvatarChangeCostumeReq_ENET_IS_RELIABLE AvatarChangeCostumeReq_CmdId = 1
	AvatarChangeCostumeReq_IS_ALLOW_CLIENT  AvatarChangeCostumeReq_CmdId = 1
	AvatarChangeCostumeReq_CMD_ID           AvatarChangeCostumeReq_CmdId = 1606
)

// Enum value maps for AvatarChangeCostumeReq_CmdId.
var (
	AvatarChangeCostumeReq_CmdId_name = map[int32]string{
		0: "ENET_CHANNEL_ID",
		// Duplicate value: 0: "NONE",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		1606: "CMD_ID",
	}
	AvatarChangeCostumeReq_CmdId_value = map[string]int32{
		"ENET_CHANNEL_ID":  0,
		"NONE":             0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           1606,
	}
)

func (x AvatarChangeCostumeReq_CmdId) Enum() *AvatarChangeCostumeReq_CmdId {
	p := new(AvatarChangeCostumeReq_CmdId)
	*p = x
	return p
}

func (x AvatarChangeCostumeReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvatarChangeCostumeReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_AvatarChangeCostumeReq_proto_enumTypes[0].Descriptor()
}

func (AvatarChangeCostumeReq_CmdId) Type() protoreflect.EnumType {
	return &file_AvatarChangeCostumeReq_proto_enumTypes[0]
}

func (x AvatarChangeCostumeReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvatarChangeCostumeReq_CmdId.Descriptor instead.
func (AvatarChangeCostumeReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_AvatarChangeCostumeReq_proto_rawDescGZIP(), []int{0, 0}
}

type AvatarChangeCostumeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarGuid uint64 `protobuf:"varint,1,opt,name=avatar_guid,json=avatarGuid,proto3" json:"avatar_guid,omitempty"`
	CostumeId  uint32 `protobuf:"varint,2,opt,name=costume_id,json=costumeId,proto3" json:"costume_id,omitempty"`
}

func (x *AvatarChangeCostumeReq) Reset() {
	*x = AvatarChangeCostumeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AvatarChangeCostumeReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarChangeCostumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarChangeCostumeReq) ProtoMessage() {}

func (x *AvatarChangeCostumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_AvatarChangeCostumeReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarChangeCostumeReq.ProtoReflect.Descriptor instead.
func (*AvatarChangeCostumeReq) Descriptor() ([]byte, []int) {
	return file_AvatarChangeCostumeReq_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarChangeCostumeReq) GetAvatarGuid() uint64 {
	if x != nil {
		return x.AvatarGuid
	}
	return 0
}

func (x *AvatarChangeCostumeReq) GetCostumeId() uint32 {
	if x != nil {
		return x.CostumeId
	}
	return 0
}

var File_AvatarChangeCostumeReq_proto protoreflect.FileDescriptor

var file_AvatarChangeCostumeReq_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f,
	0x73, 0x74, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x47, 0x75, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x49, 0x64,
	0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45,
	0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54,
	0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13,
	0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e,
	0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xc6, 0x0c,
	0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AvatarChangeCostumeReq_proto_rawDescOnce sync.Once
	file_AvatarChangeCostumeReq_proto_rawDescData = file_AvatarChangeCostumeReq_proto_rawDesc
)

func file_AvatarChangeCostumeReq_proto_rawDescGZIP() []byte {
	file_AvatarChangeCostumeReq_proto_rawDescOnce.Do(func() {
		file_AvatarChangeCostumeReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_AvatarChangeCostumeReq_proto_rawDescData)
	})
	return file_AvatarChangeCostumeReq_proto_rawDescData
}

var file_AvatarChangeCostumeReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AvatarChangeCostumeReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AvatarChangeCostumeReq_proto_goTypes = []interface{}{
	(AvatarChangeCostumeReq_CmdId)(0), // 0: proto.AvatarChangeCostumeReq.CmdId
	(*AvatarChangeCostumeReq)(nil),    // 1: proto.AvatarChangeCostumeReq
}
var file_AvatarChangeCostumeReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_AvatarChangeCostumeReq_proto_init() }
func file_AvatarChangeCostumeReq_proto_init() {
	if File_AvatarChangeCostumeReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AvatarChangeCostumeReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarChangeCostumeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AvatarChangeCostumeReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AvatarChangeCostumeReq_proto_goTypes,
		DependencyIndexes: file_AvatarChangeCostumeReq_proto_depIdxs,
		EnumInfos:         file_AvatarChangeCostumeReq_proto_enumTypes,
		MessageInfos:      file_AvatarChangeCostumeReq_proto_msgTypes,
	}.Build()
	File_AvatarChangeCostumeReq_proto = out.File
	file_AvatarChangeCostumeReq_proto_rawDesc = nil
	file_AvatarChangeCostumeReq_proto_goTypes = nil
	file_AvatarChangeCostumeReq_proto_depIdxs = nil
}
