// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: AvatarSkillInfoNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarSkillInfoNotify_CmdId int32

const (
	AvatarSkillInfoNotify_NONE             AvatarSkillInfoNotify_CmdId = 0
	AvatarSkillInfoNotify_ENET_CHANNEL_ID  AvatarSkillInfoNotify_CmdId = 0
	AvatarSkillInfoNotify_ENET_IS_RELIABLE AvatarSkillInfoNotify_CmdId = 1
	AvatarSkillInfoNotify_CMD_ID           AvatarSkillInfoNotify_CmdId = 1035
)

// Enum value maps for AvatarSkillInfoNotify_CmdId.
var (
	AvatarSkillInfoNotify_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		1035: "CMD_ID",
	}
	AvatarSkillInfoNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           1035,
	}
)

func (x AvatarSkillInfoNotify_CmdId) Enum() *AvatarSkillInfoNotify_CmdId {
	p := new(AvatarSkillInfoNotify_CmdId)
	*p = x
	return p
}

func (x AvatarSkillInfoNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvatarSkillInfoNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_AvatarSkillInfoNotify_proto_enumTypes[0].Descriptor()
}

func (AvatarSkillInfoNotify_CmdId) Type() protoreflect.EnumType {
	return &file_AvatarSkillInfoNotify_proto_enumTypes[0]
}

func (x AvatarSkillInfoNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvatarSkillInfoNotify_CmdId.Descriptor instead.
func (AvatarSkillInfoNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_AvatarSkillInfoNotify_proto_rawDescGZIP(), []int{0, 0}
}

type AvatarSkillInfoNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Guid     uint64                      `protobuf:"varint,4,opt,name=guid,proto3" json:"guid,omitempty"`
	SkillMap map[uint32]*AvatarSkillInfo `protobuf:"bytes,2,rep,name=skill_map,json=skillMap,proto3" json:"skill_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AvatarSkillInfoNotify) Reset() {
	*x = AvatarSkillInfoNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AvatarSkillInfoNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarSkillInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarSkillInfoNotify) ProtoMessage() {}

func (x *AvatarSkillInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_AvatarSkillInfoNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarSkillInfoNotify.ProtoReflect.Descriptor instead.
func (*AvatarSkillInfoNotify) Descriptor() ([]byte, []int) {
	return file_AvatarSkillInfoNotify_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarSkillInfoNotify) GetGuid() uint64 {
	if x != nil {
		return x.Guid
	}
	return 0
}

func (x *AvatarSkillInfoNotify) GetSkillMap() map[uint32]*AvatarSkillInfo {
	if x != nil {
		return x.SkillMap
	}
	return nil
}

var File_AvatarSkillInfoNotify_proto protoreflect.FileDescriptor

var file_AvatarSkillInfoNotify_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x66,
	0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x98, 0x02, 0x0a, 0x15,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x47, 0x0a, 0x09, 0x73, 0x6b, 0x69,
	0x6c, 0x6c, 0x5f, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x49, 0x6e, 0x66, 0x6f, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x4d,
	0x61, 0x70, 0x1a, 0x53, 0x0a, 0x0d, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4d, 0x61, 0x70, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e,
	0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10,
	0x8b, 0x08, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AvatarSkillInfoNotify_proto_rawDescOnce sync.Once
	file_AvatarSkillInfoNotify_proto_rawDescData = file_AvatarSkillInfoNotify_proto_rawDesc
)

func file_AvatarSkillInfoNotify_proto_rawDescGZIP() []byte {
	file_AvatarSkillInfoNotify_proto_rawDescOnce.Do(func() {
		file_AvatarSkillInfoNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_AvatarSkillInfoNotify_proto_rawDescData)
	})
	return file_AvatarSkillInfoNotify_proto_rawDescData
}

var file_AvatarSkillInfoNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AvatarSkillInfoNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_AvatarSkillInfoNotify_proto_goTypes = []interface{}{
	(AvatarSkillInfoNotify_CmdId)(0), // 0: proto.AvatarSkillInfoNotify.CmdId
	(*AvatarSkillInfoNotify)(nil),    // 1: proto.AvatarSkillInfoNotify
	nil,                              // 2: proto.AvatarSkillInfoNotify.SkillMapEntry
	(*AvatarSkillInfo)(nil),          // 3: proto.AvatarSkillInfo
}
var file_AvatarSkillInfoNotify_proto_depIdxs = []int32{
	2, // 0: proto.AvatarSkillInfoNotify.skill_map:type_name -> proto.AvatarSkillInfoNotify.SkillMapEntry
	3, // 1: proto.AvatarSkillInfoNotify.SkillMapEntry.value:type_name -> proto.AvatarSkillInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AvatarSkillInfoNotify_proto_init() }
func file_AvatarSkillInfoNotify_proto_init() {
	if File_AvatarSkillInfoNotify_proto != nil {
		return
	}
	file_AvatarSkillInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_AvatarSkillInfoNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarSkillInfoNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AvatarSkillInfoNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AvatarSkillInfoNotify_proto_goTypes,
		DependencyIndexes: file_AvatarSkillInfoNotify_proto_depIdxs,
		EnumInfos:         file_AvatarSkillInfoNotify_proto_enumTypes,
		MessageInfos:      file_AvatarSkillInfoNotify_proto_msgTypes,
	}.Build()
	File_AvatarSkillInfoNotify_proto = out.File
	file_AvatarSkillInfoNotify_proto_rawDesc = nil
	file_AvatarSkillInfoNotify_proto_goTypes = nil
	file_AvatarSkillInfoNotify_proto_depIdxs = nil
}
