// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: AvatarEquipChangeNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AvatarEquipChangeNotify_CmdId int32

const (
	AvatarEquipChangeNotify_ENET_CHANNEL_ID  AvatarEquipChangeNotify_CmdId = 0
	AvatarEquipChangeNotify_NONE             AvatarEquipChangeNotify_CmdId = 0
	AvatarEquipChangeNotify_ENET_IS_RELIABLE AvatarEquipChangeNotify_CmdId = 1
	AvatarEquipChangeNotify_IS_ALLOW_CLIENT  AvatarEquipChangeNotify_CmdId = 1
	AvatarEquipChangeNotify_CMD_ID           AvatarEquipChangeNotify_CmdId = 615
)

// Enum value maps for AvatarEquipChangeNotify_CmdId.
var (
	AvatarEquipChangeNotify_CmdId_name = map[int32]string{
		0: "ENET_CHANNEL_ID",
		// Duplicate value: 0: "NONE",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		615: "CMD_ID",
	}
	AvatarEquipChangeNotify_CmdId_value = map[string]int32{
		"ENET_CHANNEL_ID":  0,
		"NONE":             0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           615,
	}
)

func (x AvatarEquipChangeNotify_CmdId) Enum() *AvatarEquipChangeNotify_CmdId {
	p := new(AvatarEquipChangeNotify_CmdId)
	*p = x
	return p
}

func (x AvatarEquipChangeNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvatarEquipChangeNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_AvatarEquipChangeNotify_proto_enumTypes[0].Descriptor()
}

func (AvatarEquipChangeNotify_CmdId) Type() protoreflect.EnumType {
	return &file_AvatarEquipChangeNotify_proto_enumTypes[0]
}

func (x AvatarEquipChangeNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvatarEquipChangeNotify_CmdId.Descriptor instead.
func (AvatarEquipChangeNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_AvatarEquipChangeNotify_proto_rawDescGZIP(), []int{0, 0}
}

type AvatarEquipChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarGuid uint64              `protobuf:"varint,1,opt,name=avatar_guid,json=avatarGuid,proto3" json:"avatar_guid,omitempty"`
	EquipType  uint32              `protobuf:"varint,2,opt,name=equip_type,json=equipType,proto3" json:"equip_type,omitempty"`
	ItemId     uint32              `protobuf:"varint,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	EquipGuid  uint64              `protobuf:"varint,4,opt,name=equip_guid,json=equipGuid,proto3" json:"equip_guid,omitempty"`
	Weapon     *SceneWeaponInfo    `protobuf:"bytes,5,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Reliquary  *SceneReliquaryInfo `protobuf:"bytes,6,opt,name=reliquary,proto3" json:"reliquary,omitempty"`
}

func (x *AvatarEquipChangeNotify) Reset() {
	*x = AvatarEquipChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AvatarEquipChangeNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarEquipChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarEquipChangeNotify) ProtoMessage() {}

func (x *AvatarEquipChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_AvatarEquipChangeNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarEquipChangeNotify.ProtoReflect.Descriptor instead.
func (*AvatarEquipChangeNotify) Descriptor() ([]byte, []int) {
	return file_AvatarEquipChangeNotify_proto_rawDescGZIP(), []int{0}
}

func (x *AvatarEquipChangeNotify) GetAvatarGuid() uint64 {
	if x != nil {
		return x.AvatarGuid
	}
	return 0
}

func (x *AvatarEquipChangeNotify) GetEquipType() uint32 {
	if x != nil {
		return x.EquipType
	}
	return 0
}

func (x *AvatarEquipChangeNotify) GetItemId() uint32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *AvatarEquipChangeNotify) GetEquipGuid() uint64 {
	if x != nil {
		return x.EquipGuid
	}
	return 0
}

func (x *AvatarEquipChangeNotify) GetWeapon() *SceneWeaponInfo {
	if x != nil {
		return x.Weapon
	}
	return nil
}

func (x *AvatarEquipChangeNotify) GetReliquary() *SceneReliquaryInfo {
	if x != nil {
		return x.Reliquary
	}
	return nil
}

var File_AvatarEquipChangeNotify_proto protoreflect.FileDescriptor

var file_AvatarEquipChangeNotify_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x53,
	0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x6c, 0x69, 0x71, 0x75, 0x61, 0x72, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xde, 0x02, 0x0a, 0x17, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x67, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x47, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x47, 0x75, 0x69, 0x64, 0x12, 0x2e, 0x0a, 0x06, 0x77,
	0x65, 0x61, 0x70, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x12, 0x37, 0x0a, 0x09, 0x72,
	0x65, 0x6c, 0x69, 0x71, 0x75, 0x61, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x52, 0x65, 0x6c, 0x69,
	0x71, 0x75, 0x61, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x72, 0x65, 0x6c, 0x69, 0x71,
	0x75, 0x61, 0x72, 0x79, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x13, 0x0a,
	0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x43,
	0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49,
	0x44, 0x10, 0xe7, 0x04, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AvatarEquipChangeNotify_proto_rawDescOnce sync.Once
	file_AvatarEquipChangeNotify_proto_rawDescData = file_AvatarEquipChangeNotify_proto_rawDesc
)

func file_AvatarEquipChangeNotify_proto_rawDescGZIP() []byte {
	file_AvatarEquipChangeNotify_proto_rawDescOnce.Do(func() {
		file_AvatarEquipChangeNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_AvatarEquipChangeNotify_proto_rawDescData)
	})
	return file_AvatarEquipChangeNotify_proto_rawDescData
}

var file_AvatarEquipChangeNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AvatarEquipChangeNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_AvatarEquipChangeNotify_proto_goTypes = []interface{}{
	(AvatarEquipChangeNotify_CmdId)(0), // 0: proto.AvatarEquipChangeNotify.CmdId
	(*AvatarEquipChangeNotify)(nil),    // 1: proto.AvatarEquipChangeNotify
	(*SceneWeaponInfo)(nil),            // 2: proto.SceneWeaponInfo
	(*SceneReliquaryInfo)(nil),         // 3: proto.SceneReliquaryInfo
}
var file_AvatarEquipChangeNotify_proto_depIdxs = []int32{
	2, // 0: proto.AvatarEquipChangeNotify.weapon:type_name -> proto.SceneWeaponInfo
	3, // 1: proto.AvatarEquipChangeNotify.reliquary:type_name -> proto.SceneReliquaryInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_AvatarEquipChangeNotify_proto_init() }
func file_AvatarEquipChangeNotify_proto_init() {
	if File_AvatarEquipChangeNotify_proto != nil {
		return
	}
	file_SceneWeaponInfo_proto_init()
	file_SceneReliquaryInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_AvatarEquipChangeNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarEquipChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AvatarEquipChangeNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AvatarEquipChangeNotify_proto_goTypes,
		DependencyIndexes: file_AvatarEquipChangeNotify_proto_depIdxs,
		EnumInfos:         file_AvatarEquipChangeNotify_proto_enumTypes,
		MessageInfos:      file_AvatarEquipChangeNotify_proto_msgTypes,
	}.Build()
	File_AvatarEquipChangeNotify_proto = out.File
	file_AvatarEquipChangeNotify_proto_rawDesc = nil
	file_AvatarEquipChangeNotify_proto_goTypes = nil
	file_AvatarEquipChangeNotify_proto_depIdxs = nil
}
