// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: BattlePassRewardTag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattlePassRewardTag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnlockStatus BattlePassUnlockStatus `protobuf:"varint,7,opt,name=unlock_status,json=unlockStatus,proto3,enum=proto.BattlePassUnlockStatus" json:"unlock_status,omitempty"`
	Level        uint32                 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	RewardId     uint32                 `protobuf:"varint,15,opt,name=reward_id,json=rewardId,proto3" json:"reward_id,omitempty"`
}

func (x *BattlePassRewardTag) Reset() {
	*x = BattlePassRewardTag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_BattlePassRewardTag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BattlePassRewardTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattlePassRewardTag) ProtoMessage() {}

func (x *BattlePassRewardTag) ProtoReflect() protoreflect.Message {
	mi := &file_BattlePassRewardTag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattlePassRewardTag.ProtoReflect.Descriptor instead.
func (*BattlePassRewardTag) Descriptor() ([]byte, []int) {
	return file_BattlePassRewardTag_proto_rawDescGZIP(), []int{0}
}

func (x *BattlePassRewardTag) GetUnlockStatus() BattlePassUnlockStatus {
	if x != nil {
		return x.UnlockStatus
	}
	return BattlePassUnlockStatus_BATTLE_PASS_UNLOCK_STATUS_INVALID
}

func (x *BattlePassRewardTag) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *BattlePassRewardTag) GetRewardId() uint32 {
	if x != nil {
		return x.RewardId
	}
	return 0
}

var File_BattlePassRewardTag_proto protoreflect.FileDescriptor

var file_BattlePassRewardTag_proto_rawDesc = []byte{
	0x0a, 0x19, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x54, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1c, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x55, 0x6e,
	0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x8c, 0x01, 0x0a, 0x13, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x52,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x61, 0x67, 0x12, 0x42, 0x0a, 0x0d, 0x75, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0c,
	0x75, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x64, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_BattlePassRewardTag_proto_rawDescOnce sync.Once
	file_BattlePassRewardTag_proto_rawDescData = file_BattlePassRewardTag_proto_rawDesc
)

func file_BattlePassRewardTag_proto_rawDescGZIP() []byte {
	file_BattlePassRewardTag_proto_rawDescOnce.Do(func() {
		file_BattlePassRewardTag_proto_rawDescData = protoimpl.X.CompressGZIP(file_BattlePassRewardTag_proto_rawDescData)
	})
	return file_BattlePassRewardTag_proto_rawDescData
}

var file_BattlePassRewardTag_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_BattlePassRewardTag_proto_goTypes = []interface{}{
	(*BattlePassRewardTag)(nil), // 0: proto.BattlePassRewardTag
	(BattlePassUnlockStatus)(0), // 1: proto.BattlePassUnlockStatus
}
var file_BattlePassRewardTag_proto_depIdxs = []int32{
	1, // 0: proto.BattlePassRewardTag.unlock_status:type_name -> proto.BattlePassUnlockStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_BattlePassRewardTag_proto_init() }
func file_BattlePassRewardTag_proto_init() {
	if File_BattlePassRewardTag_proto != nil {
		return
	}
	file_BattlePassUnlockStatus_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_BattlePassRewardTag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BattlePassRewardTag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_BattlePassRewardTag_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_BattlePassRewardTag_proto_goTypes,
		DependencyIndexes: file_BattlePassRewardTag_proto_depIdxs,
		MessageInfos:      file_BattlePassRewardTag_proto_msgTypes,
	}.Build()
	File_BattlePassRewardTag_proto = out.File
	file_BattlePassRewardTag_proto_rawDesc = nil
	file_BattlePassRewardTag_proto_goTypes = nil
	file_BattlePassRewardTag_proto_depIdxs = nil
}
