// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: ClientCollectorDataNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientCollectorDataNotify_CmdId int32

const (
	ClientCollectorDataNotify_NONE             ClientCollectorDataNotify_CmdId = 0
	ClientCollectorDataNotify_ENET_CHANNEL_ID  ClientCollectorDataNotify_CmdId = 0
	ClientCollectorDataNotify_ENET_IS_RELIABLE ClientCollectorDataNotify_CmdId = 1
	ClientCollectorDataNotify_CMD_ID           ClientCollectorDataNotify_CmdId = 4264
)

// Enum value maps for ClientCollectorDataNotify_CmdId.
var (
	ClientCollectorDataNotify_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		4264: "CMD_ID",
	}
	ClientCollectorDataNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           4264,
	}
)

func (x ClientCollectorDataNotify_CmdId) Enum() *ClientCollectorDataNotify_CmdId {
	p := new(ClientCollectorDataNotify_CmdId)
	*p = x
	return p
}

func (x ClientCollectorDataNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientCollectorDataNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_ClientCollectorDataNotify_proto_enumTypes[0].Descriptor()
}

func (ClientCollectorDataNotify_CmdId) Type() protoreflect.EnumType {
	return &file_ClientCollectorDataNotify_proto_enumTypes[0]
}

func (x ClientCollectorDataNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientCollectorDataNotify_CmdId.Descriptor instead.
func (ClientCollectorDataNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_ClientCollectorDataNotify_proto_rawDescGZIP(), []int{0, 0}
}

type ClientCollectorDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientCollectorDataList []*ClientCollectorData `protobuf:"bytes,8,rep,name=client_collector_data_list,json=clientCollectorDataList,proto3" json:"client_collector_data_list,omitempty"`
}

func (x *ClientCollectorDataNotify) Reset() {
	*x = ClientCollectorDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientCollectorDataNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientCollectorDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientCollectorDataNotify) ProtoMessage() {}

func (x *ClientCollectorDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ClientCollectorDataNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientCollectorDataNotify.ProtoReflect.Descriptor instead.
func (*ClientCollectorDataNotify) Descriptor() ([]byte, []int) {
	return file_ClientCollectorDataNotify_proto_rawDescGZIP(), []int{0}
}

func (x *ClientCollectorDataNotify) GetClientCollectorDataList() []*ClientCollectorData {
	if x != nil {
		return x.ClientCollectorDataList
	}
	return nil
}

var File_ClientCollectorDataNotify_proto protoreflect.FileDescriptor

var file_ClientCollectorDataNotify_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc3, 0x01, 0x0a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x12, 0x57, 0x0a, 0x1a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d,
	0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a,
	0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45,
	0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f,
	0x49, 0x44, 0x10, 0xa8, 0x21, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ClientCollectorDataNotify_proto_rawDescOnce sync.Once
	file_ClientCollectorDataNotify_proto_rawDescData = file_ClientCollectorDataNotify_proto_rawDesc
)

func file_ClientCollectorDataNotify_proto_rawDescGZIP() []byte {
	file_ClientCollectorDataNotify_proto_rawDescOnce.Do(func() {
		file_ClientCollectorDataNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_ClientCollectorDataNotify_proto_rawDescData)
	})
	return file_ClientCollectorDataNotify_proto_rawDescData
}

var file_ClientCollectorDataNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ClientCollectorDataNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ClientCollectorDataNotify_proto_goTypes = []interface{}{
	(ClientCollectorDataNotify_CmdId)(0), // 0: proto.ClientCollectorDataNotify.CmdId
	(*ClientCollectorDataNotify)(nil),    // 1: proto.ClientCollectorDataNotify
	(*ClientCollectorData)(nil),          // 2: proto.ClientCollectorData
}
var file_ClientCollectorDataNotify_proto_depIdxs = []int32{
	2, // 0: proto.ClientCollectorDataNotify.client_collector_data_list:type_name -> proto.ClientCollectorData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ClientCollectorDataNotify_proto_init() }
func file_ClientCollectorDataNotify_proto_init() {
	if File_ClientCollectorDataNotify_proto != nil {
		return
	}
	file_ClientCollectorData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ClientCollectorDataNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientCollectorDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ClientCollectorDataNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ClientCollectorDataNotify_proto_goTypes,
		DependencyIndexes: file_ClientCollectorDataNotify_proto_depIdxs,
		EnumInfos:         file_ClientCollectorDataNotify_proto_enumTypes,
		MessageInfos:      file_ClientCollectorDataNotify_proto_msgTypes,
	}.Build()
	File_ClientCollectorDataNotify_proto = out.File
	file_ClientCollectorDataNotify_proto_rawDesc = nil
	file_ClientCollectorDataNotify_proto_goTypes = nil
	file_ClientCollectorDataNotify_proto_depIdxs = nil
}
