// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: EnterWorldAreaRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnterWorldAreaRsp_CmdId int32

const (
	EnterWorldAreaRsp_NONE             EnterWorldAreaRsp_CmdId = 0
	EnterWorldAreaRsp_ENET_CHANNEL_ID  EnterWorldAreaRsp_CmdId = 0
	EnterWorldAreaRsp_ENET_IS_RELIABLE EnterWorldAreaRsp_CmdId = 1
	EnterWorldAreaRsp_CMD_ID           EnterWorldAreaRsp_CmdId = 255
)

// Enum value maps for EnterWorldAreaRsp_CmdId.
var (
	EnterWorldAreaRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:   "ENET_IS_RELIABLE",
		255: "CMD_ID",
	}
	EnterWorldAreaRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           255,
	}
)

func (x EnterWorldAreaRsp_CmdId) Enum() *EnterWorldAreaRsp_CmdId {
	p := new(EnterWorldAreaRsp_CmdId)
	*p = x
	return p
}

func (x EnterWorldAreaRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnterWorldAreaRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_EnterWorldAreaRsp_proto_enumTypes[0].Descriptor()
}

func (EnterWorldAreaRsp_CmdId) Type() protoreflect.EnumType {
	return &file_EnterWorldAreaRsp_proto_enumTypes[0]
}

func (x EnterWorldAreaRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnterWorldAreaRsp_CmdId.Descriptor instead.
func (EnterWorldAreaRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_EnterWorldAreaRsp_proto_rawDescGZIP(), []int{0, 0}
}

type EnterWorldAreaRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode  int32  `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	AreaType uint32 `protobuf:"varint,2,opt,name=area_type,json=areaType,proto3" json:"area_type,omitempty"`
	AreaId   uint32 `protobuf:"varint,3,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
}

func (x *EnterWorldAreaRsp) Reset() {
	*x = EnterWorldAreaRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_EnterWorldAreaRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnterWorldAreaRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterWorldAreaRsp) ProtoMessage() {}

func (x *EnterWorldAreaRsp) ProtoReflect() protoreflect.Message {
	mi := &file_EnterWorldAreaRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterWorldAreaRsp.ProtoReflect.Descriptor instead.
func (*EnterWorldAreaRsp) Descriptor() ([]byte, []int) {
	return file_EnterWorldAreaRsp_proto_rawDescGZIP(), []int{0}
}

func (x *EnterWorldAreaRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *EnterWorldAreaRsp) GetAreaType() uint32 {
	if x != nil {
		return x.AreaType
	}
	return 0
}

func (x *EnterWorldAreaRsp) GetAreaId() uint32 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

var File_EnterWorldAreaRsp_proto protoreflect.FileDescriptor

var file_EnterWorldAreaRsp_proto_rawDesc = []byte{
	0x0a, 0x17, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x41, 0x72, 0x65, 0x61,
	0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb2, 0x01, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x41,
	0x72, 0x65, 0x61, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x72, 0x65, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a,
	0x07, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x61, 0x72, 0x65, 0x61, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45,
	0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14,
	0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42,
	0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xff,
	0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_EnterWorldAreaRsp_proto_rawDescOnce sync.Once
	file_EnterWorldAreaRsp_proto_rawDescData = file_EnterWorldAreaRsp_proto_rawDesc
)

func file_EnterWorldAreaRsp_proto_rawDescGZIP() []byte {
	file_EnterWorldAreaRsp_proto_rawDescOnce.Do(func() {
		file_EnterWorldAreaRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_EnterWorldAreaRsp_proto_rawDescData)
	})
	return file_EnterWorldAreaRsp_proto_rawDescData
}

var file_EnterWorldAreaRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_EnterWorldAreaRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_EnterWorldAreaRsp_proto_goTypes = []interface{}{
	(EnterWorldAreaRsp_CmdId)(0), // 0: proto.EnterWorldAreaRsp.CmdId
	(*EnterWorldAreaRsp)(nil),    // 1: proto.EnterWorldAreaRsp
}
var file_EnterWorldAreaRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_EnterWorldAreaRsp_proto_init() }
func file_EnterWorldAreaRsp_proto_init() {
	if File_EnterWorldAreaRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_EnterWorldAreaRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnterWorldAreaRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_EnterWorldAreaRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_EnterWorldAreaRsp_proto_goTypes,
		DependencyIndexes: file_EnterWorldAreaRsp_proto_depIdxs,
		EnumInfos:         file_EnterWorldAreaRsp_proto_enumTypes,
		MessageInfos:      file_EnterWorldAreaRsp_proto_msgTypes,
	}.Build()
	File_EnterWorldAreaRsp_proto = out.File
	file_EnterWorldAreaRsp_proto_rawDesc = nil
	file_EnterWorldAreaRsp_proto_goTypes = nil
	file_EnterWorldAreaRsp_proto_depIdxs = nil
}
