// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: GetBattlePassProductRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CmdId: 2601
// EnetChannelId: 0
// EnetIsReliable: true
type GetBattlePassProductRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode                   int32  `protobuf:"varint,13,opt,name=retcode,proto3" json:"retcode,omitempty"`
	BattlePassProductPlayType uint32 `protobuf:"varint,9,opt,name=battle_pass_product_play_type,json=battlePassProductPlayType,proto3" json:"battle_pass_product_play_type,omitempty"`
	CurScheduleId             uint32 `protobuf:"varint,12,opt,name=cur_schedule_id,json=curScheduleId,proto3" json:"cur_schedule_id,omitempty"`
	ProductId                 string `protobuf:"bytes,7,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PriceTier                 string `protobuf:"bytes,5,opt,name=price_tier,json=priceTier,proto3" json:"price_tier,omitempty"`
}

func (x *GetBattlePassProductRsp) Reset() {
	*x = GetBattlePassProductRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetBattlePassProductRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBattlePassProductRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBattlePassProductRsp) ProtoMessage() {}

func (x *GetBattlePassProductRsp) ProtoReflect() protoreflect.Message {
	mi := &file_GetBattlePassProductRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBattlePassProductRsp.ProtoReflect.Descriptor instead.
func (*GetBattlePassProductRsp) Descriptor() ([]byte, []int) {
	return file_GetBattlePassProductRsp_proto_rawDescGZIP(), []int{0}
}

func (x *GetBattlePassProductRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GetBattlePassProductRsp) GetBattlePassProductPlayType() uint32 {
	if x != nil {
		return x.BattlePassProductPlayType
	}
	return 0
}

func (x *GetBattlePassProductRsp) GetCurScheduleId() uint32 {
	if x != nil {
		return x.CurScheduleId
	}
	return 0
}

func (x *GetBattlePassProductRsp) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetBattlePassProductRsp) GetPriceTier() string {
	if x != nil {
		return x.PriceTier
	}
	return ""
}

var File_GetBattlePassProductRsp_proto protoreflect.FileDescriptor

var file_GetBattlePassProductRsp_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x40, 0x0a, 0x1d,
	0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x19, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x50, 0x61, 0x73, 0x73, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26,
	0x0a, 0x0f, 0x63, 0x75, 0x72, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x74,
	0x69, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x54, 0x69, 0x65, 0x72, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetBattlePassProductRsp_proto_rawDescOnce sync.Once
	file_GetBattlePassProductRsp_proto_rawDescData = file_GetBattlePassProductRsp_proto_rawDesc
)

func file_GetBattlePassProductRsp_proto_rawDescGZIP() []byte {
	file_GetBattlePassProductRsp_proto_rawDescOnce.Do(func() {
		file_GetBattlePassProductRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetBattlePassProductRsp_proto_rawDescData)
	})
	return file_GetBattlePassProductRsp_proto_rawDescData
}

var file_GetBattlePassProductRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetBattlePassProductRsp_proto_goTypes = []interface{}{
	(*GetBattlePassProductRsp)(nil), // 0: proto.GetBattlePassProductRsp
}
var file_GetBattlePassProductRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GetBattlePassProductRsp_proto_init() }
func file_GetBattlePassProductRsp_proto_init() {
	if File_GetBattlePassProductRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GetBattlePassProductRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBattlePassProductRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetBattlePassProductRsp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetBattlePassProductRsp_proto_goTypes,
		DependencyIndexes: file_GetBattlePassProductRsp_proto_depIdxs,
		MessageInfos:      file_GetBattlePassProductRsp_proto_msgTypes,
	}.Build()
	File_GetBattlePassProductRsp_proto = out.File
	file_GetBattlePassProductRsp_proto_rawDesc = nil
	file_GetBattlePassProductRsp_proto_goTypes = nil
	file_GetBattlePassProductRsp_proto_depIdxs = nil
}
