// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: GetPlayerFriendListRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayerFriendListRsp_CmdId int32

const (
	GetPlayerFriendListRsp_NONE             GetPlayerFriendListRsp_CmdId = 0
	GetPlayerFriendListRsp_ENET_CHANNEL_ID  GetPlayerFriendListRsp_CmdId = 0
	GetPlayerFriendListRsp_ENET_IS_RELIABLE GetPlayerFriendListRsp_CmdId = 1
	GetPlayerFriendListRsp_IS_ALLOW_CLIENT  GetPlayerFriendListRsp_CmdId = 1
	GetPlayerFriendListRsp_CMD_ID           GetPlayerFriendListRsp_CmdId = 4031
)

// Enum value maps for GetPlayerFriendListRsp_CmdId.
var (
	GetPlayerFriendListRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		4031: "CMD_ID",
	}
	GetPlayerFriendListRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           4031,
	}
)

func (x GetPlayerFriendListRsp_CmdId) Enum() *GetPlayerFriendListRsp_CmdId {
	p := new(GetPlayerFriendListRsp_CmdId)
	*p = x
	return p
}

func (x GetPlayerFriendListRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPlayerFriendListRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_GetPlayerFriendListRsp_proto_enumTypes[0].Descriptor()
}

func (GetPlayerFriendListRsp_CmdId) Type() protoreflect.EnumType {
	return &file_GetPlayerFriendListRsp_proto_enumTypes[0]
}

func (x GetPlayerFriendListRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPlayerFriendListRsp_CmdId.Descriptor instead.
func (GetPlayerFriendListRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_GetPlayerFriendListRsp_proto_rawDescGZIP(), []int{0, 0}
}

type GetPlayerFriendListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode       int32          `protobuf:"varint,3,opt,name=retcode,proto3" json:"retcode,omitempty"`
	FriendList    []*FriendBrief `protobuf:"bytes,6,rep,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`
	AskFriendList []*FriendBrief `protobuf:"bytes,5,rep,name=ask_friend_list,json=askFriendList,proto3" json:"ask_friend_list,omitempty"`
}

func (x *GetPlayerFriendListRsp) Reset() {
	*x = GetPlayerFriendListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GetPlayerFriendListRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerFriendListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerFriendListRsp) ProtoMessage() {}

func (x *GetPlayerFriendListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_GetPlayerFriendListRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerFriendListRsp.ProtoReflect.Descriptor instead.
func (*GetPlayerFriendListRsp) Descriptor() ([]byte, []int) {
	return file_GetPlayerFriendListRsp_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayerFriendListRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *GetPlayerFriendListRsp) GetFriendList() []*FriendBrief {
	if x != nil {
		return x.FriendList
	}
	return nil
}

func (x *GetPlayerFriendListRsp) GetAskFriendList() []*FriendBrief {
	if x != nil {
		return x.AskFriendList
	}
	return nil
}

var File_GetPlayerFriendListRsp_proto protoreflect.FileDescriptor

var file_GetPlayerFriendListRsp_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42, 0x72, 0x69,
	0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x02, 0x0a, 0x16, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x33, 0x0a,
	0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x3a, 0x0a, 0x0f, 0x61, 0x73, 0x6b, 0x5f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x42, 0x72, 0x69, 0x65, 0x66, 0x52,
	0x0d, 0x61, 0x73, 0x6b, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x62,
	0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45,
	0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49,
	0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f,
	0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xbf, 0x1f, 0x1a, 0x02,
	0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GetPlayerFriendListRsp_proto_rawDescOnce sync.Once
	file_GetPlayerFriendListRsp_proto_rawDescData = file_GetPlayerFriendListRsp_proto_rawDesc
)

func file_GetPlayerFriendListRsp_proto_rawDescGZIP() []byte {
	file_GetPlayerFriendListRsp_proto_rawDescOnce.Do(func() {
		file_GetPlayerFriendListRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_GetPlayerFriendListRsp_proto_rawDescData)
	})
	return file_GetPlayerFriendListRsp_proto_rawDescData
}

var file_GetPlayerFriendListRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_GetPlayerFriendListRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_GetPlayerFriendListRsp_proto_goTypes = []interface{}{
	(GetPlayerFriendListRsp_CmdId)(0), // 0: proto.GetPlayerFriendListRsp.CmdId
	(*GetPlayerFriendListRsp)(nil),    // 1: proto.GetPlayerFriendListRsp
	(*FriendBrief)(nil),               // 2: proto.FriendBrief
}
var file_GetPlayerFriendListRsp_proto_depIdxs = []int32{
	2, // 0: proto.GetPlayerFriendListRsp.friend_list:type_name -> proto.FriendBrief
	2, // 1: proto.GetPlayerFriendListRsp.ask_friend_list:type_name -> proto.FriendBrief
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_GetPlayerFriendListRsp_proto_init() }
func file_GetPlayerFriendListRsp_proto_init() {
	if File_GetPlayerFriendListRsp_proto != nil {
		return
	}
	file_FriendBrief_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_GetPlayerFriendListRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerFriendListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GetPlayerFriendListRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_GetPlayerFriendListRsp_proto_goTypes,
		DependencyIndexes: file_GetPlayerFriendListRsp_proto_depIdxs,
		EnumInfos:         file_GetPlayerFriendListRsp_proto_enumTypes,
		MessageInfos:      file_GetPlayerFriendListRsp_proto_msgTypes,
	}.Build()
	File_GetPlayerFriendListRsp_proto = out.File
	file_GetPlayerFriendListRsp_proto_rawDesc = nil
	file_GetPlayerFriendListRsp_proto_goTypes = nil
	file_GetPlayerFriendListRsp_proto_depIdxs = nil
}
