// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: ItemExceedLimitNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemExceedLimitNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsMaterialExceedLimit  bool     `protobuf:"varint,1,opt,name=isMaterialExceedLimit,proto3" json:"isMaterialExceedLimit,omitempty"`
	IsWeaponExceedLimit    bool     `protobuf:"varint,2,opt,name=isWeaponExceedLimit,proto3" json:"isWeaponExceedLimit,omitempty"`
	IsReliquaryExceedLimit bool     `protobuf:"varint,3,opt,name=isReliquaryExceedLimit,proto3" json:"isReliquaryExceedLimit,omitempty"`
	ItemIdList             []uint32 `protobuf:"varint,4,rep,packed,name=itemIdList,proto3" json:"itemIdList,omitempty"`
}

func (x *ItemExceedLimitNotify) Reset() {
	*x = ItemExceedLimitNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ItemExceedLimitNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemExceedLimitNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemExceedLimitNotify) ProtoMessage() {}

func (x *ItemExceedLimitNotify) ProtoReflect() protoreflect.Message {
	mi := &file_ItemExceedLimitNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemExceedLimitNotify.ProtoReflect.Descriptor instead.
func (*ItemExceedLimitNotify) Descriptor() ([]byte, []int) {
	return file_ItemExceedLimitNotify_proto_rawDescGZIP(), []int{0}
}

func (x *ItemExceedLimitNotify) GetIsMaterialExceedLimit() bool {
	if x != nil {
		return x.IsMaterialExceedLimit
	}
	return false
}

func (x *ItemExceedLimitNotify) GetIsWeaponExceedLimit() bool {
	if x != nil {
		return x.IsWeaponExceedLimit
	}
	return false
}

func (x *ItemExceedLimitNotify) GetIsReliquaryExceedLimit() bool {
	if x != nil {
		return x.IsReliquaryExceedLimit
	}
	return false
}

func (x *ItemExceedLimitNotify) GetItemIdList() []uint32 {
	if x != nil {
		return x.ItemIdList
	}
	return nil
}

var File_ItemExceedLimitNotify_proto protoreflect.FileDescriptor

var file_ItemExceedLimitNotify_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x78, 0x63, 0x65, 0x65, 0x64, 0x4c, 0x69, 0x6d, 0x69,
	0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x15, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x78, 0x63,
	0x65, 0x65, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x34,
	0x0a, 0x15, 0x69, 0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x45, 0x78, 0x63, 0x65,
	0x65, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x69,
	0x73, 0x4d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x45, 0x78, 0x63, 0x65, 0x65, 0x64, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x69, 0x73, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e,
	0x45, 0x78, 0x63, 0x65, 0x65, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x13, 0x69, 0x73, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x45, 0x78, 0x63, 0x65, 0x65,
	0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x69, 0x73, 0x52, 0x65, 0x6c, 0x69,
	0x71, 0x75, 0x61, 0x72, 0x79, 0x45, 0x78, 0x63, 0x65, 0x65, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x16, 0x69, 0x73, 0x52, 0x65, 0x6c, 0x69, 0x71, 0x75,
	0x61, 0x72, 0x79, 0x45, 0x78, 0x63, 0x65, 0x65, 0x64, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x0a, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ItemExceedLimitNotify_proto_rawDescOnce sync.Once
	file_ItemExceedLimitNotify_proto_rawDescData = file_ItemExceedLimitNotify_proto_rawDesc
)

func file_ItemExceedLimitNotify_proto_rawDescGZIP() []byte {
	file_ItemExceedLimitNotify_proto_rawDescOnce.Do(func() {
		file_ItemExceedLimitNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_ItemExceedLimitNotify_proto_rawDescData)
	})
	return file_ItemExceedLimitNotify_proto_rawDescData
}

var file_ItemExceedLimitNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ItemExceedLimitNotify_proto_goTypes = []interface{}{
	(*ItemExceedLimitNotify)(nil), // 0: proto.ItemExceedLimitNotify
}
var file_ItemExceedLimitNotify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ItemExceedLimitNotify_proto_init() }
func file_ItemExceedLimitNotify_proto_init() {
	if File_ItemExceedLimitNotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ItemExceedLimitNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemExceedLimitNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ItemExceedLimitNotify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ItemExceedLimitNotify_proto_goTypes,
		DependencyIndexes: file_ItemExceedLimitNotify_proto_depIdxs,
		MessageInfos:      file_ItemExceedLimitNotify_proto_msgTypes,
	}.Build()
	File_ItemExceedLimitNotify_proto = out.File
	file_ItemExceedLimitNotify_proto_rawDesc = nil
	file_ItemExceedLimitNotify_proto_goTypes = nil
	file_ItemExceedLimitNotify_proto_depIdxs = nil
}
