// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: MailChangeNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailChangeNotify_CmdId int32

const (
	MailChangeNotify_NONE             MailChangeNotify_CmdId = 0
	MailChangeNotify_ENET_CHANNEL_ID  MailChangeNotify_CmdId = 0
	MailChangeNotify_ENET_IS_RELIABLE MailChangeNotify_CmdId = 1
	MailChangeNotify_CMD_ID           MailChangeNotify_CmdId = 1431
)

// Enum value maps for MailChangeNotify_CmdId.
var (
	MailChangeNotify_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		1431: "CMD_ID",
	}
	MailChangeNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           1431,
	}
)

func (x MailChangeNotify_CmdId) Enum() *MailChangeNotify_CmdId {
	p := new(MailChangeNotify_CmdId)
	*p = x
	return p
}

func (x MailChangeNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailChangeNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_MailChangeNotify_proto_enumTypes[0].Descriptor()
}

func (MailChangeNotify_CmdId) Type() protoreflect.EnumType {
	return &file_MailChangeNotify_proto_enumTypes[0]
}

func (x MailChangeNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailChangeNotify_CmdId.Descriptor instead.
func (MailChangeNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_MailChangeNotify_proto_rawDescGZIP(), []int{0, 0}
}

type MailChangeNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MailList      []*MailData `protobuf:"bytes,3,rep,name=mail_list,json=mailList,proto3" json:"mail_list,omitempty"`
	DelMailIdList []uint32    `protobuf:"varint,7,rep,packed,name=del_mail_id_list,json=delMailIdList,proto3" json:"del_mail_id_list,omitempty"`
}

func (x *MailChangeNotify) Reset() {
	*x = MailChangeNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MailChangeNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailChangeNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailChangeNotify) ProtoMessage() {}

func (x *MailChangeNotify) ProtoReflect() protoreflect.Message {
	mi := &file_MailChangeNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailChangeNotify.ProtoReflect.Descriptor instead.
func (*MailChangeNotify) Descriptor() ([]byte, []int) {
	return file_MailChangeNotify_proto_rawDescGZIP(), []int{0}
}

func (x *MailChangeNotify) GetMailList() []*MailData {
	if x != nil {
		return x.MailList
	}
	return nil
}

func (x *MailChangeNotify) GetDelMailIdList() []uint32 {
	if x != nil {
		return x.DelMailIdList
	}
	return nil
}

var File_MailChangeNotify_proto protoreflect.FileDescriptor

var file_MailChangeNotify_proto_rawDesc = []byte{
	0x0a, 0x16, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0e, 0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xb8, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x12, 0x2c, 0x0a, 0x09, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4d, 0x61, 0x69, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x61, 0x69, 0x6c, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x27, 0x0a, 0x10, 0x64, 0x65, 0x6c, 0x5f, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x69,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x64, 0x65,
	0x6c, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x05, 0x43,
	0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52,
	0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44,
	0x5f, 0x49, 0x44, 0x10, 0x97, 0x0b, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MailChangeNotify_proto_rawDescOnce sync.Once
	file_MailChangeNotify_proto_rawDescData = file_MailChangeNotify_proto_rawDesc
)

func file_MailChangeNotify_proto_rawDescGZIP() []byte {
	file_MailChangeNotify_proto_rawDescOnce.Do(func() {
		file_MailChangeNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_MailChangeNotify_proto_rawDescData)
	})
	return file_MailChangeNotify_proto_rawDescData
}

var file_MailChangeNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MailChangeNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MailChangeNotify_proto_goTypes = []interface{}{
	(MailChangeNotify_CmdId)(0), // 0: proto.MailChangeNotify.CmdId
	(*MailChangeNotify)(nil),    // 1: proto.MailChangeNotify
	(*MailData)(nil),            // 2: proto.MailData
}
var file_MailChangeNotify_proto_depIdxs = []int32{
	2, // 0: proto.MailChangeNotify.mail_list:type_name -> proto.MailData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_MailChangeNotify_proto_init() }
func file_MailChangeNotify_proto_init() {
	if File_MailChangeNotify_proto != nil {
		return
	}
	file_MailData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_MailChangeNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailChangeNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MailChangeNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MailChangeNotify_proto_goTypes,
		DependencyIndexes: file_MailChangeNotify_proto_depIdxs,
		EnumInfos:         file_MailChangeNotify_proto_enumTypes,
		MessageInfos:      file_MailChangeNotify_proto_msgTypes,
	}.Build()
	File_MailChangeNotify_proto = out.File
	file_MailChangeNotify_proto_rawDesc = nil
	file_MailChangeNotify_proto_goTypes = nil
	file_MailChangeNotify_proto_depIdxs = nil
}
