// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: MarkMapReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkMapReq_CmdId int32

const (
	MarkMapReq_ENET_CHANNEL_ID  MarkMapReq_CmdId = 0
	MarkMapReq_NONE             MarkMapReq_CmdId = 0
	MarkMapReq_ENET_IS_RELIABLE MarkMapReq_CmdId = 1
	MarkMapReq_IS_ALLOW_CLIENT  MarkMapReq_CmdId = 1
	MarkMapReq_CMD_ID           MarkMapReq_CmdId = 3216
)

// Enum value maps for MarkMapReq_CmdId.
var (
	MarkMapReq_CmdId_name = map[int32]string{
		0: "ENET_CHANNEL_ID",
		// Duplicate value: 0: "NONE",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		3216: "CMD_ID",
	}
	MarkMapReq_CmdId_value = map[string]int32{
		"ENET_CHANNEL_ID":  0,
		"NONE":             0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           3216,
	}
)

func (x MarkMapReq_CmdId) Enum() *MarkMapReq_CmdId {
	p := new(MarkMapReq_CmdId)
	*p = x
	return p
}

func (x MarkMapReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarkMapReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_MarkMapReq_proto_enumTypes[0].Descriptor()
}

func (MarkMapReq_CmdId) Type() protoreflect.EnumType {
	return &file_MarkMapReq_proto_enumTypes[0]
}

func (x MarkMapReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarkMapReq_CmdId.Descriptor instead.
func (MarkMapReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_MarkMapReq_proto_rawDescGZIP(), []int{0, 0}
}

type MarkMapReq_Operation int32

const (
	MarkMapReq_ADD MarkMapReq_Operation = 0
	MarkMapReq_MOD MarkMapReq_Operation = 1
	MarkMapReq_DEL MarkMapReq_Operation = 2
	MarkMapReq_GET MarkMapReq_Operation = 3
)

// Enum value maps for MarkMapReq_Operation.
var (
	MarkMapReq_Operation_name = map[int32]string{
		0: "ADD",
		1: "MOD",
		2: "DEL",
		3: "GET",
	}
	MarkMapReq_Operation_value = map[string]int32{
		"ADD": 0,
		"MOD": 1,
		"DEL": 2,
		"GET": 3,
	}
)

func (x MarkMapReq_Operation) Enum() *MarkMapReq_Operation {
	p := new(MarkMapReq_Operation)
	*p = x
	return p
}

func (x MarkMapReq_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarkMapReq_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_MarkMapReq_proto_enumTypes[1].Descriptor()
}

func (MarkMapReq_Operation) Type() protoreflect.EnumType {
	return &file_MarkMapReq_proto_enumTypes[1]
}

func (x MarkMapReq_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarkMapReq_Operation.Descriptor instead.
func (MarkMapReq_Operation) EnumDescriptor() ([]byte, []int) {
	return file_MarkMapReq_proto_rawDescGZIP(), []int{0, 1}
}

type MarkMapReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op   MarkMapReq_Operation `protobuf:"varint,1,opt,name=op,proto3,enum=proto.MarkMapReq_Operation" json:"op,omitempty"`
	Old  *MapMarkPoint        `protobuf:"bytes,2,opt,name=old,proto3" json:"old,omitempty"`
	Mark *MapMarkPoint        `protobuf:"bytes,3,opt,name=mark,proto3" json:"mark,omitempty"`
}

func (x *MarkMapReq) Reset() {
	*x = MarkMapReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MarkMapReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkMapReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMapReq) ProtoMessage() {}

func (x *MarkMapReq) ProtoReflect() protoreflect.Message {
	mi := &file_MarkMapReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMapReq.ProtoReflect.Descriptor instead.
func (*MarkMapReq) Descriptor() ([]byte, []int) {
	return file_MarkMapReq_proto_rawDescGZIP(), []int{0}
}

func (x *MarkMapReq) GetOp() MarkMapReq_Operation {
	if x != nil {
		return x.Op
	}
	return MarkMapReq_ADD
}

func (x *MarkMapReq) GetOld() *MapMarkPoint {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *MarkMapReq) GetMark() *MapMarkPoint {
	if x != nil {
		return x.Mark
	}
	return nil
}

var File_MarkMapReq_proto protoreflect.FileDescriptor

var file_MarkMapReq_proto_rawDesc = []byte{
	0x0a, 0x10, 0x4d, 0x61, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x61, 0x70, 0x4d, 0x61,
	0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x9e, 0x02,
	0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x02,
	0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x65, 0x71, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x25, 0x0a, 0x03, 0x6f, 0x6c, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d,
	0x61, 0x70, 0x4d, 0x61, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x03, 0x6f, 0x6c, 0x64,
	0x12, 0x27, 0x0a, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x4d, 0x61, 0x72, 0x6b, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64,
	0x49, 0x64, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c,
	0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c,
	0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06,
	0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x90, 0x19, 0x1a, 0x02, 0x10, 0x01, 0x22, 0x2f, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44,
	0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x4f, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x44, 0x45, 0x4c, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x03, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_MarkMapReq_proto_rawDescOnce sync.Once
	file_MarkMapReq_proto_rawDescData = file_MarkMapReq_proto_rawDesc
)

func file_MarkMapReq_proto_rawDescGZIP() []byte {
	file_MarkMapReq_proto_rawDescOnce.Do(func() {
		file_MarkMapReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_MarkMapReq_proto_rawDescData)
	})
	return file_MarkMapReq_proto_rawDescData
}

var file_MarkMapReq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_MarkMapReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MarkMapReq_proto_goTypes = []interface{}{
	(MarkMapReq_CmdId)(0),     // 0: proto.MarkMapReq.CmdId
	(MarkMapReq_Operation)(0), // 1: proto.MarkMapReq.Operation
	(*MarkMapReq)(nil),        // 2: proto.MarkMapReq
	(*MapMarkPoint)(nil),      // 3: proto.MapMarkPoint
}
var file_MarkMapReq_proto_depIdxs = []int32{
	1, // 0: proto.MarkMapReq.op:type_name -> proto.MarkMapReq.Operation
	3, // 1: proto.MarkMapReq.old:type_name -> proto.MapMarkPoint
	3, // 2: proto.MarkMapReq.mark:type_name -> proto.MapMarkPoint
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_MarkMapReq_proto_init() }
func file_MarkMapReq_proto_init() {
	if File_MarkMapReq_proto != nil {
		return
	}
	file_MapMarkPoint_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_MarkMapReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkMapReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MarkMapReq_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MarkMapReq_proto_goTypes,
		DependencyIndexes: file_MarkMapReq_proto_depIdxs,
		EnumInfos:         file_MarkMapReq_proto_enumTypes,
		MessageInfos:      file_MarkMapReq_proto_msgTypes,
	}.Build()
	File_MarkMapReq_proto = out.File
	file_MarkMapReq_proto_rawDesc = nil
	file_MarkMapReq_proto_goTypes = nil
	file_MarkMapReq_proto_depIdxs = nil
}
