// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: MarkMapRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MarkMapRsp_CmdId int32

const (
	MarkMapRsp_NONE             MarkMapRsp_CmdId = 0
	MarkMapRsp_ENET_CHANNEL_ID  MarkMapRsp_CmdId = 0
	MarkMapRsp_ENET_IS_RELIABLE MarkMapRsp_CmdId = 1
	MarkMapRsp_CMD_ID           MarkMapRsp_CmdId = 3421
)

// Enum value maps for MarkMapRsp_CmdId.
var (
	MarkMapRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		3421: "CMD_ID",
	}
	MarkMapRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           3421,
	}
)

func (x MarkMapRsp_CmdId) Enum() *MarkMapRsp_CmdId {
	p := new(MarkMapRsp_CmdId)
	*p = x
	return p
}

func (x MarkMapRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarkMapRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_MarkMapRsp_proto_enumTypes[0].Descriptor()
}

func (MarkMapRsp_CmdId) Type() protoreflect.EnumType {
	return &file_MarkMapRsp_proto_enumTypes[0]
}

func (x MarkMapRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarkMapRsp_CmdId.Descriptor instead.
func (MarkMapRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_MarkMapRsp_proto_rawDescGZIP(), []int{0, 0}
}

type MarkMapRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode  int32           `protobuf:"varint,11,opt,name=retcode,proto3" json:"retcode,omitempty"`
	MarkList []*MapMarkPoint `protobuf:"bytes,7,rep,name=mark_list,json=markList,proto3" json:"mark_list,omitempty"`
}

func (x *MarkMapRsp) Reset() {
	*x = MarkMapRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MarkMapRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkMapRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkMapRsp) ProtoMessage() {}

func (x *MarkMapRsp) ProtoReflect() protoreflect.Message {
	mi := &file_MarkMapRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkMapRsp.ProtoReflect.Descriptor instead.
func (*MarkMapRsp) Descriptor() ([]byte, []int) {
	return file_MarkMapRsp_proto_rawDescGZIP(), []int{0}
}

func (x *MarkMapRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *MarkMapRsp) GetMarkList() []*MapMarkPoint {
	if x != nil {
		return x.MarkList
	}
	return nil
}

var File_MarkMapRsp_proto protoreflect.FileDescriptor

var file_MarkMapRsp_proto_rawDesc = []byte{
	0x0a, 0x10, 0x4d, 0x61, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x4d, 0x61, 0x70, 0x4d, 0x61,
	0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01,
	0x0a, 0x0a, 0x4d, 0x61, 0x72, 0x6b, 0x4d, 0x61, 0x70, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72,
	0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4d, 0x61, 0x70, 0x4d, 0x61, 0x72, 0x6b, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x08,
	0x6d, 0x61, 0x72, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49,
	0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45,
	0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44,
	0x10, 0xdd, 0x1a, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_MarkMapRsp_proto_rawDescOnce sync.Once
	file_MarkMapRsp_proto_rawDescData = file_MarkMapRsp_proto_rawDesc
)

func file_MarkMapRsp_proto_rawDescGZIP() []byte {
	file_MarkMapRsp_proto_rawDescOnce.Do(func() {
		file_MarkMapRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_MarkMapRsp_proto_rawDescData)
	})
	return file_MarkMapRsp_proto_rawDescData
}

var file_MarkMapRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MarkMapRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_MarkMapRsp_proto_goTypes = []interface{}{
	(MarkMapRsp_CmdId)(0), // 0: proto.MarkMapRsp.CmdId
	(*MarkMapRsp)(nil),    // 1: proto.MarkMapRsp
	(*MapMarkPoint)(nil),  // 2: proto.MapMarkPoint
}
var file_MarkMapRsp_proto_depIdxs = []int32{
	2, // 0: proto.MarkMapRsp.mark_list:type_name -> proto.MapMarkPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_MarkMapRsp_proto_init() }
func file_MarkMapRsp_proto_init() {
	if File_MarkMapRsp_proto != nil {
		return
	}
	file_MapMarkPoint_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_MarkMapRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkMapRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MarkMapRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MarkMapRsp_proto_goTypes,
		DependencyIndexes: file_MarkMapRsp_proto_depIdxs,
		EnumInfos:         file_MarkMapRsp_proto_enumTypes,
		MessageInfos:      file_MarkMapRsp_proto_msgTypes,
	}.Build()
	File_MarkMapRsp_proto = out.File
	file_MarkMapRsp_proto_rawDesc = nil
	file_MarkMapRsp_proto_goTypes = nil
	file_MarkMapRsp_proto_depIdxs = nil
}
