// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: OneoffGatherPointDetectorDataNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneoffGatherPointDetectorDataNotify_CmdId int32

const (
	OneoffGatherPointDetectorDataNotify_NONE             OneoffGatherPointDetectorDataNotify_CmdId = 0
	OneoffGatherPointDetectorDataNotify_ENET_CHANNEL_ID  OneoffGatherPointDetectorDataNotify_CmdId = 0
	OneoffGatherPointDetectorDataNotify_ENET_IS_RELIABLE OneoffGatherPointDetectorDataNotify_CmdId = 1
	OneoffGatherPointDetectorDataNotify_CMD_ID           OneoffGatherPointDetectorDataNotify_CmdId = 4262
)

// Enum value maps for OneoffGatherPointDetectorDataNotify_CmdId.
var (
	OneoffGatherPointDetectorDataNotify_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		4262: "CMD_ID",
	}
	OneoffGatherPointDetectorDataNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           4262,
	}
)

func (x OneoffGatherPointDetectorDataNotify_CmdId) Enum() *OneoffGatherPointDetectorDataNotify_CmdId {
	p := new(OneoffGatherPointDetectorDataNotify_CmdId)
	*p = x
	return p
}

func (x OneoffGatherPointDetectorDataNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OneoffGatherPointDetectorDataNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_OneoffGatherPointDetectorDataNotify_proto_enumTypes[0].Descriptor()
}

func (OneoffGatherPointDetectorDataNotify_CmdId) Type() protoreflect.EnumType {
	return &file_OneoffGatherPointDetectorDataNotify_proto_enumTypes[0]
}

func (x OneoffGatherPointDetectorDataNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OneoffGatherPointDetectorDataNotify_CmdId.Descriptor instead.
func (OneoffGatherPointDetectorDataNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_OneoffGatherPointDetectorDataNotify_proto_rawDescGZIP(), []int{0, 0}
}

type OneoffGatherPointDetectorDataNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OneoffGatherPointDetectorDataList []*OneoffGatherPointDetectorData `protobuf:"bytes,6,rep,name=oneoff_gather_point_detector_data_list,json=oneoffGatherPointDetectorDataList,proto3" json:"oneoff_gather_point_detector_data_list,omitempty"`
}

func (x *OneoffGatherPointDetectorDataNotify) Reset() {
	*x = OneoffGatherPointDetectorDataNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OneoffGatherPointDetectorDataNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OneoffGatherPointDetectorDataNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneoffGatherPointDetectorDataNotify) ProtoMessage() {}

func (x *OneoffGatherPointDetectorDataNotify) ProtoReflect() protoreflect.Message {
	mi := &file_OneoffGatherPointDetectorDataNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneoffGatherPointDetectorDataNotify.ProtoReflect.Descriptor instead.
func (*OneoffGatherPointDetectorDataNotify) Descriptor() ([]byte, []int) {
	return file_OneoffGatherPointDetectorDataNotify_proto_rawDescGZIP(), []int{0}
}

func (x *OneoffGatherPointDetectorDataNotify) GetOneoffGatherPointDetectorDataList() []*OneoffGatherPointDetectorData {
	if x != nil {
		return x.OneoffGatherPointDetectorDataList
	}
	return nil
}

var File_OneoffGatherPointDetectorDataNotify_proto protoreflect.FileDescriptor

var file_OneoffGatherPointDetectorDataNotify_proto_rawDesc = []byte{
	0x0a, 0x29, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x66, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x23, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x66, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xed, 0x01, 0x0a, 0x23, 0x4f, 0x6e, 0x65, 0x6f,
	0x66, 0x66, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x77, 0x0a, 0x26, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x66, 0x5f, 0x67, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x66, 0x47, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x21, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x66, 0x47, 0x61, 0x74,
	0x68, 0x65, 0x72, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49,
	0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45,
	0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49,
	0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44,
	0x10, 0xa6, 0x21, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OneoffGatherPointDetectorDataNotify_proto_rawDescOnce sync.Once
	file_OneoffGatherPointDetectorDataNotify_proto_rawDescData = file_OneoffGatherPointDetectorDataNotify_proto_rawDesc
)

func file_OneoffGatherPointDetectorDataNotify_proto_rawDescGZIP() []byte {
	file_OneoffGatherPointDetectorDataNotify_proto_rawDescOnce.Do(func() {
		file_OneoffGatherPointDetectorDataNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_OneoffGatherPointDetectorDataNotify_proto_rawDescData)
	})
	return file_OneoffGatherPointDetectorDataNotify_proto_rawDescData
}

var file_OneoffGatherPointDetectorDataNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_OneoffGatherPointDetectorDataNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_OneoffGatherPointDetectorDataNotify_proto_goTypes = []interface{}{
	(OneoffGatherPointDetectorDataNotify_CmdId)(0), // 0: proto.OneoffGatherPointDetectorDataNotify.CmdId
	(*OneoffGatherPointDetectorDataNotify)(nil),    // 1: proto.OneoffGatherPointDetectorDataNotify
	(*OneoffGatherPointDetectorData)(nil),          // 2: proto.OneoffGatherPointDetectorData
}
var file_OneoffGatherPointDetectorDataNotify_proto_depIdxs = []int32{
	2, // 0: proto.OneoffGatherPointDetectorDataNotify.oneoff_gather_point_detector_data_list:type_name -> proto.OneoffGatherPointDetectorData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_OneoffGatherPointDetectorDataNotify_proto_init() }
func file_OneoffGatherPointDetectorDataNotify_proto_init() {
	if File_OneoffGatherPointDetectorDataNotify_proto != nil {
		return
	}
	file_OneoffGatherPointDetectorData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_OneoffGatherPointDetectorDataNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OneoffGatherPointDetectorDataNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OneoffGatherPointDetectorDataNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_OneoffGatherPointDetectorDataNotify_proto_goTypes,
		DependencyIndexes: file_OneoffGatherPointDetectorDataNotify_proto_depIdxs,
		EnumInfos:         file_OneoffGatherPointDetectorDataNotify_proto_enumTypes,
		MessageInfos:      file_OneoffGatherPointDetectorDataNotify_proto_msgTypes,
	}.Build()
	File_OneoffGatherPointDetectorDataNotify_proto = out.File
	file_OneoffGatherPointDetectorDataNotify_proto_rawDesc = nil
	file_OneoffGatherPointDetectorDataNotify_proto_goTypes = nil
	file_OneoffGatherPointDetectorDataNotify_proto_depIdxs = nil
}
