// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: PlayerQuitDungeonReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerQuitDungeonReq_CmdId int32

const (
	PlayerQuitDungeonReq_NONE             PlayerQuitDungeonReq_CmdId = 0
	PlayerQuitDungeonReq_ENET_CHANNEL_ID  PlayerQuitDungeonReq_CmdId = 0
	PlayerQuitDungeonReq_ENET_IS_RELIABLE PlayerQuitDungeonReq_CmdId = 1
	PlayerQuitDungeonReq_IS_ALLOW_CLIENT  PlayerQuitDungeonReq_CmdId = 1
	PlayerQuitDungeonReq_CMD_ID           PlayerQuitDungeonReq_CmdId = 932
)

// Enum value maps for PlayerQuitDungeonReq_CmdId.
var (
	PlayerQuitDungeonReq_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		932: "CMD_ID",
	}
	PlayerQuitDungeonReq_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           932,
	}
)

func (x PlayerQuitDungeonReq_CmdId) Enum() *PlayerQuitDungeonReq_CmdId {
	p := new(PlayerQuitDungeonReq_CmdId)
	*p = x
	return p
}

func (x PlayerQuitDungeonReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerQuitDungeonReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PlayerQuitDungeonReq_proto_enumTypes[0].Descriptor()
}

func (PlayerQuitDungeonReq_CmdId) Type() protoreflect.EnumType {
	return &file_PlayerQuitDungeonReq_proto_enumTypes[0]
}

func (x PlayerQuitDungeonReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerQuitDungeonReq_CmdId.Descriptor instead.
func (PlayerQuitDungeonReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PlayerQuitDungeonReq_proto_rawDescGZIP(), []int{0, 0}
}

type PlayerQuitDungeonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PointId           uint32 `protobuf:"varint,12,opt,name=point_id,json=pointId,proto3" json:"point_id,omitempty"`
	IsQuitImmediately bool   `protobuf:"varint,4,opt,name=is_quit_immediately,json=isQuitImmediately,proto3" json:"is_quit_immediately,omitempty"`
}

func (x *PlayerQuitDungeonReq) Reset() {
	*x = PlayerQuitDungeonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PlayerQuitDungeonReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerQuitDungeonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQuitDungeonReq) ProtoMessage() {}

func (x *PlayerQuitDungeonReq) ProtoReflect() protoreflect.Message {
	mi := &file_PlayerQuitDungeonReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQuitDungeonReq.ProtoReflect.Descriptor instead.
func (*PlayerQuitDungeonReq) Descriptor() ([]byte, []int) {
	return file_PlayerQuitDungeonReq_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerQuitDungeonReq) GetPointId() uint32 {
	if x != nil {
		return x.PointId
	}
	return 0
}

func (x *PlayerQuitDungeonReq) GetIsQuitImmediately() bool {
	if x != nil {
		return x.IsQuitImmediately
	}
	return false
}

var File_PlayerQuitDungeonReq_proto protoreflect.FileDescriptor

var file_PlayerQuitDungeonReq_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75, 0x69, 0x74, 0x44, 0x75, 0x6e, 0x67,
	0x65, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x51, 0x75,
	0x69, 0x74, 0x44, 0x75, 0x6e, 0x67, 0x65, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x69, 0x73, 0x5f, 0x71, 0x75,
	0x69, 0x74, 0x5f, 0x69, 0x6d, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x73, 0x51, 0x75, 0x69, 0x74, 0x49, 0x6d, 0x6d, 0x65,
	0x64, 0x69, 0x61, 0x74, 0x65, 0x6c, 0x79, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e,
	0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f,
	0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d,
	0x44, 0x5f, 0x49, 0x44, 0x10, 0xa4, 0x07, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PlayerQuitDungeonReq_proto_rawDescOnce sync.Once
	file_PlayerQuitDungeonReq_proto_rawDescData = file_PlayerQuitDungeonReq_proto_rawDesc
)

func file_PlayerQuitDungeonReq_proto_rawDescGZIP() []byte {
	file_PlayerQuitDungeonReq_proto_rawDescOnce.Do(func() {
		file_PlayerQuitDungeonReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_PlayerQuitDungeonReq_proto_rawDescData)
	})
	return file_PlayerQuitDungeonReq_proto_rawDescData
}

var file_PlayerQuitDungeonReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PlayerQuitDungeonReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PlayerQuitDungeonReq_proto_goTypes = []interface{}{
	(PlayerQuitDungeonReq_CmdId)(0), // 0: proto.PlayerQuitDungeonReq.CmdId
	(*PlayerQuitDungeonReq)(nil),    // 1: proto.PlayerQuitDungeonReq
}
var file_PlayerQuitDungeonReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PlayerQuitDungeonReq_proto_init() }
func file_PlayerQuitDungeonReq_proto_init() {
	if File_PlayerQuitDungeonReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PlayerQuitDungeonReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerQuitDungeonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PlayerQuitDungeonReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PlayerQuitDungeonReq_proto_goTypes,
		DependencyIndexes: file_PlayerQuitDungeonReq_proto_depIdxs,
		EnumInfos:         file_PlayerQuitDungeonReq_proto_enumTypes,
		MessageInfos:      file_PlayerQuitDungeonReq_proto_msgTypes,
	}.Build()
	File_PlayerQuitDungeonReq_proto = out.File
	file_PlayerQuitDungeonReq_proto_rawDesc = nil
	file_PlayerQuitDungeonReq_proto_goTypes = nil
	file_PlayerQuitDungeonReq_proto_depIdxs = nil
}
