// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: PullPrivateChatReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullPrivateChatReq_CmdId int32

const (
	PullPrivateChatReq_ENET_CHANNEL_ID  PullPrivateChatReq_CmdId = 0
	PullPrivateChatReq_NONE             PullPrivateChatReq_CmdId = 0
	PullPrivateChatReq_ENET_IS_RELIABLE PullPrivateChatReq_CmdId = 1
	PullPrivateChatReq_IS_ALLOW_CLIENT  PullPrivateChatReq_CmdId = 1
	PullPrivateChatReq_CMD_ID           PullPrivateChatReq_CmdId = 4951
)

// Enum value maps for PullPrivateChatReq_CmdId.
var (
	PullPrivateChatReq_CmdId_name = map[int32]string{
		0: "ENET_CHANNEL_ID",
		// Duplicate value: 0: "NONE",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		4951: "CMD_ID",
	}
	PullPrivateChatReq_CmdId_value = map[string]int32{
		"ENET_CHANNEL_ID":  0,
		"NONE":             0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           4951,
	}
)

func (x PullPrivateChatReq_CmdId) Enum() *PullPrivateChatReq_CmdId {
	p := new(PullPrivateChatReq_CmdId)
	*p = x
	return p
}

func (x PullPrivateChatReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullPrivateChatReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PullPrivateChatReq_proto_enumTypes[0].Descriptor()
}

func (PullPrivateChatReq_CmdId) Type() protoreflect.EnumType {
	return &file_PullPrivateChatReq_proto_enumTypes[0]
}

func (x PullPrivateChatReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullPrivateChatReq_CmdId.Descriptor instead.
func (PullPrivateChatReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PullPrivateChatReq_proto_rawDescGZIP(), []int{0, 0}
}

type PullPrivateChatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetUid    uint32 `protobuf:"varint,1,opt,name=target_uid,json=targetUid,proto3" json:"target_uid,omitempty"`
	FromSequence uint32 `protobuf:"varint,2,opt,name=from_sequence,json=fromSequence,proto3" json:"from_sequence,omitempty"`
	PullNum      uint32 `protobuf:"varint,3,opt,name=pull_num,json=pullNum,proto3" json:"pull_num,omitempty"`
}

func (x *PullPrivateChatReq) Reset() {
	*x = PullPrivateChatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PullPrivateChatReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullPrivateChatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullPrivateChatReq) ProtoMessage() {}

func (x *PullPrivateChatReq) ProtoReflect() protoreflect.Message {
	mi := &file_PullPrivateChatReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullPrivateChatReq.ProtoReflect.Descriptor instead.
func (*PullPrivateChatReq) Descriptor() ([]byte, []int) {
	return file_PullPrivateChatReq_proto_rawDescGZIP(), []int{0}
}

func (x *PullPrivateChatReq) GetTargetUid() uint32 {
	if x != nil {
		return x.TargetUid
	}
	return 0
}

func (x *PullPrivateChatReq) GetFromSequence() uint32 {
	if x != nil {
		return x.FromSequence
	}
	return 0
}

func (x *PullPrivateChatReq) GetPullNum() uint32 {
	if x != nil {
		return x.PullNum
	}
	return 0
}

var File_PullPrivateChatReq_proto protoreflect.FileDescriptor

var file_PullPrivateChatReq_proto_rawDesc = []byte{
	0x0a, 0x18, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd7, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x55, 0x69, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x5f,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x66, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x70, 0x75, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64,
	0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c,
	0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41,
	0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c, 0x4c, 0x4f,
	0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d,
	0x44, 0x5f, 0x49, 0x44, 0x10, 0xd7, 0x26, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PullPrivateChatReq_proto_rawDescOnce sync.Once
	file_PullPrivateChatReq_proto_rawDescData = file_PullPrivateChatReq_proto_rawDesc
)

func file_PullPrivateChatReq_proto_rawDescGZIP() []byte {
	file_PullPrivateChatReq_proto_rawDescOnce.Do(func() {
		file_PullPrivateChatReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_PullPrivateChatReq_proto_rawDescData)
	})
	return file_PullPrivateChatReq_proto_rawDescData
}

var file_PullPrivateChatReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PullPrivateChatReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PullPrivateChatReq_proto_goTypes = []interface{}{
	(PullPrivateChatReq_CmdId)(0), // 0: proto.PullPrivateChatReq.CmdId
	(*PullPrivateChatReq)(nil),    // 1: proto.PullPrivateChatReq
}
var file_PullPrivateChatReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_PullPrivateChatReq_proto_init() }
func file_PullPrivateChatReq_proto_init() {
	if File_PullPrivateChatReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PullPrivateChatReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullPrivateChatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PullPrivateChatReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PullPrivateChatReq_proto_goTypes,
		DependencyIndexes: file_PullPrivateChatReq_proto_depIdxs,
		EnumInfos:         file_PullPrivateChatReq_proto_enumTypes,
		MessageInfos:      file_PullPrivateChatReq_proto_msgTypes,
	}.Build()
	File_PullPrivateChatReq_proto = out.File
	file_PullPrivateChatReq_proto_rawDesc = nil
	file_PullPrivateChatReq_proto_goTypes = nil
	file_PullPrivateChatReq_proto_depIdxs = nil
}
