// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: PullPrivateChatRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullPrivateChatRsp_CmdId int32

const (
	PullPrivateChatRsp_NONE             PullPrivateChatRsp_CmdId = 0
	PullPrivateChatRsp_ENET_CHANNEL_ID  PullPrivateChatRsp_CmdId = 0
	PullPrivateChatRsp_ENET_IS_RELIABLE PullPrivateChatRsp_CmdId = 1
	PullPrivateChatRsp_CMD_ID           PullPrivateChatRsp_CmdId = 5044
)

// Enum value maps for PullPrivateChatRsp_CmdId.
var (
	PullPrivateChatRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		5044: "CMD_ID",
	}
	PullPrivateChatRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           5044,
	}
)

func (x PullPrivateChatRsp_CmdId) Enum() *PullPrivateChatRsp_CmdId {
	p := new(PullPrivateChatRsp_CmdId)
	*p = x
	return p
}

func (x PullPrivateChatRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullPrivateChatRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_PullPrivateChatRsp_proto_enumTypes[0].Descriptor()
}

func (PullPrivateChatRsp_CmdId) Type() protoreflect.EnumType {
	return &file_PullPrivateChatRsp_proto_enumTypes[0]
}

func (x PullPrivateChatRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullPrivateChatRsp_CmdId.Descriptor instead.
func (PullPrivateChatRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_PullPrivateChatRsp_proto_rawDescGZIP(), []int{0, 0}
}

type PullPrivateChatRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode  int32       `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	ChatInfo []*ChatInfo `protobuf:"bytes,2,rep,name=chat_info,json=chatInfo,proto3" json:"chat_info,omitempty"`
}

func (x *PullPrivateChatRsp) Reset() {
	*x = PullPrivateChatRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PullPrivateChatRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullPrivateChatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullPrivateChatRsp) ProtoMessage() {}

func (x *PullPrivateChatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_PullPrivateChatRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullPrivateChatRsp.ProtoReflect.Descriptor instead.
func (*PullPrivateChatRsp) Descriptor() ([]byte, []int) {
	return file_PullPrivateChatRsp_proto_rawDescGZIP(), []int{0}
}

func (x *PullPrivateChatRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *PullPrivateChatRsp) GetChatInfo() []*ChatInfo {
	if x != nil {
		return x.ChatInfo
	}
	return nil
}

var File_PullPrivateChatRsp_proto protoreflect.FileDescriptor

var file_PullPrivateChatRsp_proto_rawDesc = []byte{
	0x0a, 0x18, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xab, 0x01, 0x0a, 0x12, 0x50, 0x75, 0x6c, 0x6c, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x43, 0x68, 0x61, 0x74, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e,
	0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54,
	0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xb4, 0x27, 0x1a, 0x02, 0x10, 0x01, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_PullPrivateChatRsp_proto_rawDescOnce sync.Once
	file_PullPrivateChatRsp_proto_rawDescData = file_PullPrivateChatRsp_proto_rawDesc
)

func file_PullPrivateChatRsp_proto_rawDescGZIP() []byte {
	file_PullPrivateChatRsp_proto_rawDescOnce.Do(func() {
		file_PullPrivateChatRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_PullPrivateChatRsp_proto_rawDescData)
	})
	return file_PullPrivateChatRsp_proto_rawDescData
}

var file_PullPrivateChatRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_PullPrivateChatRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_PullPrivateChatRsp_proto_goTypes = []interface{}{
	(PullPrivateChatRsp_CmdId)(0), // 0: proto.PullPrivateChatRsp.CmdId
	(*PullPrivateChatRsp)(nil),    // 1: proto.PullPrivateChatRsp
	(*ChatInfo)(nil),              // 2: proto.ChatInfo
}
var file_PullPrivateChatRsp_proto_depIdxs = []int32{
	2, // 0: proto.PullPrivateChatRsp.chat_info:type_name -> proto.ChatInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PullPrivateChatRsp_proto_init() }
func file_PullPrivateChatRsp_proto_init() {
	if File_PullPrivateChatRsp_proto != nil {
		return
	}
	file_ChatInfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_PullPrivateChatRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullPrivateChatRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PullPrivateChatRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_PullPrivateChatRsp_proto_goTypes,
		DependencyIndexes: file_PullPrivateChatRsp_proto_depIdxs,
		EnumInfos:         file_PullPrivateChatRsp_proto_enumTypes,
		MessageInfos:      file_PullPrivateChatRsp_proto_msgTypes,
	}.Build()
	File_PullPrivateChatRsp_proto = out.File
	file_PullPrivateChatRsp_proto_rawDesc = nil
	file_PullPrivateChatRsp_proto_goTypes = nil
	file_PullPrivateChatRsp_proto_depIdxs = nil
}
