// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: QueryCodexMonsterBeKilledNumRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryCodexMonsterBeKilledNumRsp_CmdId int32

const (
	QueryCodexMonsterBeKilledNumRsp_NONE             QueryCodexMonsterBeKilledNumRsp_CmdId = 0
	QueryCodexMonsterBeKilledNumRsp_ENET_CHANNEL_ID  QueryCodexMonsterBeKilledNumRsp_CmdId = 0
	QueryCodexMonsterBeKilledNumRsp_ENET_IS_RELIABLE QueryCodexMonsterBeKilledNumRsp_CmdId = 1
	QueryCodexMonsterBeKilledNumRsp_CMD_ID           QueryCodexMonsterBeKilledNumRsp_CmdId = 4205
)

// Enum value maps for QueryCodexMonsterBeKilledNumRsp_CmdId.
var (
	QueryCodexMonsterBeKilledNumRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		4205: "CMD_ID",
	}
	QueryCodexMonsterBeKilledNumRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           4205,
	}
)

func (x QueryCodexMonsterBeKilledNumRsp_CmdId) Enum() *QueryCodexMonsterBeKilledNumRsp_CmdId {
	p := new(QueryCodexMonsterBeKilledNumRsp_CmdId)
	*p = x
	return p
}

func (x QueryCodexMonsterBeKilledNumRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryCodexMonsterBeKilledNumRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_QueryCodexMonsterBeKilledNumRsp_proto_enumTypes[0].Descriptor()
}

func (QueryCodexMonsterBeKilledNumRsp_CmdId) Type() protoreflect.EnumType {
	return &file_QueryCodexMonsterBeKilledNumRsp_proto_enumTypes[0]
}

func (x QueryCodexMonsterBeKilledNumRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryCodexMonsterBeKilledNumRsp_CmdId.Descriptor instead.
func (QueryCodexMonsterBeKilledNumRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescGZIP(), []int{0, 0}
}

type QueryCodexMonsterBeKilledNumRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode         int32    `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	CodexIdList     []uint32 `protobuf:"varint,4,rep,packed,name=codex_id_list,json=codexIdList,proto3" json:"codex_id_list,omitempty"`
	BeKilledNumList []uint32 `protobuf:"varint,11,rep,packed,name=be_killed_num_list,json=beKilledNumList,proto3" json:"be_killed_num_list,omitempty"`
	CHPBKCLKPCJ     []uint32 `protobuf:"varint,2,rep,packed,name=CHPBKCLKPCJ,proto3" json:"CHPBKCLKPCJ,omitempty"`
}

func (x *QueryCodexMonsterBeKilledNumRsp) Reset() {
	*x = QueryCodexMonsterBeKilledNumRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QueryCodexMonsterBeKilledNumRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryCodexMonsterBeKilledNumRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCodexMonsterBeKilledNumRsp) ProtoMessage() {}

func (x *QueryCodexMonsterBeKilledNumRsp) ProtoReflect() protoreflect.Message {
	mi := &file_QueryCodexMonsterBeKilledNumRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCodexMonsterBeKilledNumRsp.ProtoReflect.Descriptor instead.
func (*QueryCodexMonsterBeKilledNumRsp) Descriptor() ([]byte, []int) {
	return file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescGZIP(), []int{0}
}

func (x *QueryCodexMonsterBeKilledNumRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *QueryCodexMonsterBeKilledNumRsp) GetCodexIdList() []uint32 {
	if x != nil {
		return x.CodexIdList
	}
	return nil
}

func (x *QueryCodexMonsterBeKilledNumRsp) GetBeKilledNumList() []uint32 {
	if x != nil {
		return x.BeKilledNumList
	}
	return nil
}

func (x *QueryCodexMonsterBeKilledNumRsp) GetCHPBKCLKPCJ() []uint32 {
	if x != nil {
		return x.CHPBKCLKPCJ
	}
	return nil
}

var File_QueryCodexMonsterBeKilledNumRsp_proto protoreflect.FileDescriptor

var file_QueryCodexMonsterBeKilledNumRsp_proto_rawDesc = []byte{
	0x0a, 0x25, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x4d, 0x6f, 0x6e, 0x73,
	0x74, 0x65, 0x72, 0x42, 0x65, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x73,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfd,
	0x01, 0x0a, 0x1f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x78, 0x4d, 0x6f, 0x6e,
	0x73, 0x74, 0x65, 0x72, 0x42, 0x65, 0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x52,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0d,
	0x63, 0x6f, 0x64, 0x65, 0x78, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6f, 0x64, 0x65, 0x78, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2b, 0x0a, 0x12, 0x62, 0x65, 0x5f, 0x6b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x5f, 0x6e, 0x75,
	0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0f, 0x62, 0x65,
	0x4b, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x4e, 0x75, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x48, 0x50, 0x42, 0x4b, 0x43, 0x4c, 0x4b, 0x50, 0x43, 0x4a, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0d, 0x52, 0x0b, 0x43, 0x48, 0x50, 0x42, 0x4b, 0x43, 0x4c, 0x4b, 0x50, 0x43, 0x4a, 0x22,
	0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f,
	0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xed, 0x20, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescOnce sync.Once
	file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescData = file_QueryCodexMonsterBeKilledNumRsp_proto_rawDesc
)

func file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescGZIP() []byte {
	file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescOnce.Do(func() {
		file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescData)
	})
	return file_QueryCodexMonsterBeKilledNumRsp_proto_rawDescData
}

var file_QueryCodexMonsterBeKilledNumRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_QueryCodexMonsterBeKilledNumRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_QueryCodexMonsterBeKilledNumRsp_proto_goTypes = []interface{}{
	(QueryCodexMonsterBeKilledNumRsp_CmdId)(0), // 0: proto.QueryCodexMonsterBeKilledNumRsp.CmdId
	(*QueryCodexMonsterBeKilledNumRsp)(nil),    // 1: proto.QueryCodexMonsterBeKilledNumRsp
}
var file_QueryCodexMonsterBeKilledNumRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_QueryCodexMonsterBeKilledNumRsp_proto_init() }
func file_QueryCodexMonsterBeKilledNumRsp_proto_init() {
	if File_QueryCodexMonsterBeKilledNumRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_QueryCodexMonsterBeKilledNumRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryCodexMonsterBeKilledNumRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_QueryCodexMonsterBeKilledNumRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_QueryCodexMonsterBeKilledNumRsp_proto_goTypes,
		DependencyIndexes: file_QueryCodexMonsterBeKilledNumRsp_proto_depIdxs,
		EnumInfos:         file_QueryCodexMonsterBeKilledNumRsp_proto_enumTypes,
		MessageInfos:      file_QueryCodexMonsterBeKilledNumRsp_proto_msgTypes,
	}.Build()
	File_QueryCodexMonsterBeKilledNumRsp_proto = out.File
	file_QueryCodexMonsterBeKilledNumRsp_proto_rawDesc = nil
	file_QueryCodexMonsterBeKilledNumRsp_proto_goTypes = nil
	file_QueryCodexMonsterBeKilledNumRsp_proto_depIdxs = nil
}
