// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: QuickUseWidgetRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuickUseWidgetRsp_CmdId int32

const (
	QuickUseWidgetRsp_NONE             QuickUseWidgetRsp_CmdId = 0
	QuickUseWidgetRsp_ENET_CHANNEL_ID  QuickUseWidgetRsp_CmdId = 0
	QuickUseWidgetRsp_ENET_IS_RELIABLE QuickUseWidgetRsp_CmdId = 1
	QuickUseWidgetRsp_CMD_ID           QuickUseWidgetRsp_CmdId = 4252
)

// Enum value maps for QuickUseWidgetRsp_CmdId.
var (
	QuickUseWidgetRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		4252: "CMD_ID",
	}
	QuickUseWidgetRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           4252,
	}
)

func (x QuickUseWidgetRsp_CmdId) Enum() *QuickUseWidgetRsp_CmdId {
	p := new(QuickUseWidgetRsp_CmdId)
	*p = x
	return p
}

func (x QuickUseWidgetRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuickUseWidgetRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_QuickUseWidgetRsp_proto_enumTypes[0].Descriptor()
}

func (QuickUseWidgetRsp_CmdId) Type() protoreflect.EnumType {
	return &file_QuickUseWidgetRsp_proto_enumTypes[0]
}

func (x QuickUseWidgetRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuickUseWidgetRsp_CmdId.Descriptor instead.
func (QuickUseWidgetRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_QuickUseWidgetRsp_proto_rawDescGZIP(), []int{0, 0}
}

type QuickUseWidgetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode             int32                          `protobuf:"varint,9,opt,name=retcode,proto3" json:"retcode,omitempty"`
	MaterialId          uint32                         `protobuf:"varint,1,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
	DetectorData        *OneoffGatherPointDetectorData `protobuf:"bytes,3,opt,name=detector_data,json=detectorData,proto3" json:"detector_data,omitempty"`
	ClientCollectorData *ClientCollectorData           `protobuf:"bytes,4,opt,name=client_collector_data,json=clientCollectorData,proto3" json:"client_collector_data,omitempty"`
}

func (x *QuickUseWidgetRsp) Reset() {
	*x = QuickUseWidgetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QuickUseWidgetRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuickUseWidgetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuickUseWidgetRsp) ProtoMessage() {}

func (x *QuickUseWidgetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_QuickUseWidgetRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuickUseWidgetRsp.ProtoReflect.Descriptor instead.
func (*QuickUseWidgetRsp) Descriptor() ([]byte, []int) {
	return file_QuickUseWidgetRsp_proto_rawDescGZIP(), []int{0}
}

func (x *QuickUseWidgetRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *QuickUseWidgetRsp) GetMaterialId() uint32 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

func (x *QuickUseWidgetRsp) GetDetectorData() *OneoffGatherPointDetectorData {
	if x != nil {
		return x.DetectorData
	}
	return nil
}

func (x *QuickUseWidgetRsp) GetClientCollectorData() *ClientCollectorData {
	if x != nil {
		return x.ClientCollectorData
	}
	return nil
}

var File_QuickUseWidgetRsp_proto protoreflect.FileDescriptor

var file_QuickUseWidgetRsp_proto_rawDesc = []byte{
	0x0a, 0x17, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74,
	0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x23, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x66, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xb8, 0x02, 0x0a, 0x11, 0x51, 0x75, 0x69, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x57, 0x69, 0x64,
	0x67, 0x65, 0x74, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49,
	0x64, 0x12, 0x49, 0x0a, 0x0d, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4f, 0x6e, 0x65, 0x6f, 0x66, 0x66, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6f, 0x69,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x0c,
	0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4e, 0x0a, 0x15,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52, 0x13, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4d, 0x0a, 0x05,
	0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f,
	0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f,
	0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d,
	0x44, 0x5f, 0x49, 0x44, 0x10, 0x9c, 0x21, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_QuickUseWidgetRsp_proto_rawDescOnce sync.Once
	file_QuickUseWidgetRsp_proto_rawDescData = file_QuickUseWidgetRsp_proto_rawDesc
)

func file_QuickUseWidgetRsp_proto_rawDescGZIP() []byte {
	file_QuickUseWidgetRsp_proto_rawDescOnce.Do(func() {
		file_QuickUseWidgetRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_QuickUseWidgetRsp_proto_rawDescData)
	})
	return file_QuickUseWidgetRsp_proto_rawDescData
}

var file_QuickUseWidgetRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_QuickUseWidgetRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_QuickUseWidgetRsp_proto_goTypes = []interface{}{
	(QuickUseWidgetRsp_CmdId)(0),          // 0: proto.QuickUseWidgetRsp.CmdId
	(*QuickUseWidgetRsp)(nil),             // 1: proto.QuickUseWidgetRsp
	(*OneoffGatherPointDetectorData)(nil), // 2: proto.OneoffGatherPointDetectorData
	(*ClientCollectorData)(nil),           // 3: proto.ClientCollectorData
}
var file_QuickUseWidgetRsp_proto_depIdxs = []int32{
	2, // 0: proto.QuickUseWidgetRsp.detector_data:type_name -> proto.OneoffGatherPointDetectorData
	3, // 1: proto.QuickUseWidgetRsp.client_collector_data:type_name -> proto.ClientCollectorData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_QuickUseWidgetRsp_proto_init() }
func file_QuickUseWidgetRsp_proto_init() {
	if File_QuickUseWidgetRsp_proto != nil {
		return
	}
	file_OneoffGatherPointDetectorData_proto_init()
	file_ClientCollectorData_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_QuickUseWidgetRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuickUseWidgetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_QuickUseWidgetRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_QuickUseWidgetRsp_proto_goTypes,
		DependencyIndexes: file_QuickUseWidgetRsp_proto_depIdxs,
		EnumInfos:         file_QuickUseWidgetRsp_proto_enumTypes,
		MessageInfos:      file_QuickUseWidgetRsp_proto_msgTypes,
	}.Build()
	File_QuickUseWidgetRsp_proto = out.File
	file_QuickUseWidgetRsp_proto_rawDesc = nil
	file_QuickUseWidgetRsp_proto_goTypes = nil
	file_QuickUseWidgetRsp_proto_depIdxs = nil
}
