// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: SceneEntityDisappearNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneEntityDisappearNotify_CmdId int32

const (
	SceneEntityDisappearNotify_NONE             SceneEntityDisappearNotify_CmdId = 0
	SceneEntityDisappearNotify_ENET_CHANNEL_ID  SceneEntityDisappearNotify_CmdId = 0
	SceneEntityDisappearNotify_ENET_IS_RELIABLE SceneEntityDisappearNotify_CmdId = 1
	SceneEntityDisappearNotify_CMD_ID           SceneEntityDisappearNotify_CmdId = 285
)

// Enum value maps for SceneEntityDisappearNotify_CmdId.
var (
	SceneEntityDisappearNotify_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:   "ENET_IS_RELIABLE",
		285: "CMD_ID",
	}
	SceneEntityDisappearNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           285,
	}
)

func (x SceneEntityDisappearNotify_CmdId) Enum() *SceneEntityDisappearNotify_CmdId {
	p := new(SceneEntityDisappearNotify_CmdId)
	*p = x
	return p
}

func (x SceneEntityDisappearNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneEntityDisappearNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_SceneEntityDisappearNotify_proto_enumTypes[0].Descriptor()
}

func (SceneEntityDisappearNotify_CmdId) Type() protoreflect.EnumType {
	return &file_SceneEntityDisappearNotify_proto_enumTypes[0]
}

func (x SceneEntityDisappearNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneEntityDisappearNotify_CmdId.Descriptor instead.
func (SceneEntityDisappearNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_SceneEntityDisappearNotify_proto_rawDescGZIP(), []int{0, 0}
}

type SceneEntityDisappearNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntityList    []uint32   `protobuf:"varint,9,rep,packed,name=entity_list,json=entityList,proto3" json:"entity_list,omitempty"`
	DisappearType VisionType `protobuf:"varint,10,opt,name=disappear_type,json=disappearType,proto3,enum=proto.VisionType" json:"disappear_type,omitempty"`
	Param         uint32     `protobuf:"varint,6,opt,name=param,proto3" json:"param,omitempty"`
}

func (x *SceneEntityDisappearNotify) Reset() {
	*x = SceneEntityDisappearNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneEntityDisappearNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneEntityDisappearNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneEntityDisappearNotify) ProtoMessage() {}

func (x *SceneEntityDisappearNotify) ProtoReflect() protoreflect.Message {
	mi := &file_SceneEntityDisappearNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneEntityDisappearNotify.ProtoReflect.Descriptor instead.
func (*SceneEntityDisappearNotify) Descriptor() ([]byte, []int) {
	return file_SceneEntityDisappearNotify_proto_rawDescGZIP(), []int{0}
}

func (x *SceneEntityDisappearNotify) GetEntityList() []uint32 {
	if x != nil {
		return x.EntityList
	}
	return nil
}

func (x *SceneEntityDisappearNotify) GetDisappearType() VisionType {
	if x != nil {
		return x.DisappearType
	}
	return VisionType_VISION_TYPE_NONE
}

func (x *SceneEntityDisappearNotify) GetParam() uint32 {
	if x != nil {
		return x.Param
	}
	return 0
}

var File_SceneEntityDisappearNotify_proto protoreflect.FileDescriptor

var file_SceneEntityDisappearNotify_proto_rawDesc = []byte{
	0x0a, 0x20, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x69, 0x73,
	0x61, 0x70, 0x70, 0x65, 0x61, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x56, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x01, 0x0a, 0x1a,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x44, 0x69, 0x73, 0x61, 0x70,
	0x70, 0x65, 0x61, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0d, 0x52,
	0x0a, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0e, 0x64,
	0x69, 0x73, 0x61, 0x70, 0x70, 0x65, 0x61, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x61, 0x70, 0x70, 0x65, 0x61,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x22, 0x4d, 0x0a, 0x05, 0x43,
	0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52,
	0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44,
	0x5f, 0x49, 0x44, 0x10, 0x9d, 0x02, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SceneEntityDisappearNotify_proto_rawDescOnce sync.Once
	file_SceneEntityDisappearNotify_proto_rawDescData = file_SceneEntityDisappearNotify_proto_rawDesc
)

func file_SceneEntityDisappearNotify_proto_rawDescGZIP() []byte {
	file_SceneEntityDisappearNotify_proto_rawDescOnce.Do(func() {
		file_SceneEntityDisappearNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneEntityDisappearNotify_proto_rawDescData)
	})
	return file_SceneEntityDisappearNotify_proto_rawDescData
}

var file_SceneEntityDisappearNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SceneEntityDisappearNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneEntityDisappearNotify_proto_goTypes = []interface{}{
	(SceneEntityDisappearNotify_CmdId)(0), // 0: proto.SceneEntityDisappearNotify.CmdId
	(*SceneEntityDisappearNotify)(nil),    // 1: proto.SceneEntityDisappearNotify
	(VisionType)(0),                       // 2: proto.VisionType
}
var file_SceneEntityDisappearNotify_proto_depIdxs = []int32{
	2, // 0: proto.SceneEntityDisappearNotify.disappear_type:type_name -> proto.VisionType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SceneEntityDisappearNotify_proto_init() }
func file_SceneEntityDisappearNotify_proto_init() {
	if File_SceneEntityDisappearNotify_proto != nil {
		return
	}
	file_VisionType_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SceneEntityDisappearNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneEntityDisappearNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneEntityDisappearNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneEntityDisappearNotify_proto_goTypes,
		DependencyIndexes: file_SceneEntityDisappearNotify_proto_depIdxs,
		EnumInfos:         file_SceneEntityDisappearNotify_proto_enumTypes,
		MessageInfos:      file_SceneEntityDisappearNotify_proto_msgTypes,
	}.Build()
	File_SceneEntityDisappearNotify_proto = out.File
	file_SceneEntityDisappearNotify_proto_rawDesc = nil
	file_SceneEntityDisappearNotify_proto_goTypes = nil
	file_SceneEntityDisappearNotify_proto_depIdxs = nil
}
