// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: SceneForceUnlockNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneForceUnlockNotify_CmdId int32

const (
	SceneForceUnlockNotify_NONE             SceneForceUnlockNotify_CmdId = 0
	SceneForceUnlockNotify_ENET_CHANNEL_ID  SceneForceUnlockNotify_CmdId = 0
	SceneForceUnlockNotify_ENET_IS_RELIABLE SceneForceUnlockNotify_CmdId = 1
	SceneForceUnlockNotify_CMD_ID           SceneForceUnlockNotify_CmdId = 201
)

// Enum value maps for SceneForceUnlockNotify_CmdId.
var (
	SceneForceUnlockNotify_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:   "ENET_IS_RELIABLE",
		201: "CMD_ID",
	}
	SceneForceUnlockNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           201,
	}
)

func (x SceneForceUnlockNotify_CmdId) Enum() *SceneForceUnlockNotify_CmdId {
	p := new(SceneForceUnlockNotify_CmdId)
	*p = x
	return p
}

func (x SceneForceUnlockNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneForceUnlockNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_SceneForceUnlockNotify_proto_enumTypes[0].Descriptor()
}

func (SceneForceUnlockNotify_CmdId) Type() protoreflect.EnumType {
	return &file_SceneForceUnlockNotify_proto_enumTypes[0]
}

func (x SceneForceUnlockNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneForceUnlockNotify_CmdId.Descriptor instead.
func (SceneForceUnlockNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_SceneForceUnlockNotify_proto_rawDescGZIP(), []int{0, 0}
}

type SceneForceUnlockNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ForceIdList []uint32 `protobuf:"varint,1,rep,packed,name=force_id_list,json=forceIdList,proto3" json:"force_id_list,omitempty"`
	IsAdd       bool     `protobuf:"varint,5,opt,name=is_add,json=isAdd,proto3" json:"is_add,omitempty"`
}

func (x *SceneForceUnlockNotify) Reset() {
	*x = SceneForceUnlockNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneForceUnlockNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneForceUnlockNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneForceUnlockNotify) ProtoMessage() {}

func (x *SceneForceUnlockNotify) ProtoReflect() protoreflect.Message {
	mi := &file_SceneForceUnlockNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneForceUnlockNotify.ProtoReflect.Descriptor instead.
func (*SceneForceUnlockNotify) Descriptor() ([]byte, []int) {
	return file_SceneForceUnlockNotify_proto_rawDescGZIP(), []int{0}
}

func (x *SceneForceUnlockNotify) GetForceIdList() []uint32 {
	if x != nil {
		return x.ForceIdList
	}
	return nil
}

func (x *SceneForceUnlockNotify) GetIsAdd() bool {
	if x != nil {
		return x.IsAdd
	}
	return false
}

var File_SceneForceUnlockNotify_proto protoreflect.FileDescriptor

var file_SceneForceUnlockNotify_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x6e, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x01, 0x0a, 0x16, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x46,
	0x6f, 0x72, 0x63, 0x65, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x22, 0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x49, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x41, 0x64, 0x64, 0x22, 0x4d, 0x0a, 0x05, 0x43,
	0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52,
	0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44,
	0x5f, 0x49, 0x44, 0x10, 0xc9, 0x01, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SceneForceUnlockNotify_proto_rawDescOnce sync.Once
	file_SceneForceUnlockNotify_proto_rawDescData = file_SceneForceUnlockNotify_proto_rawDesc
)

func file_SceneForceUnlockNotify_proto_rawDescGZIP() []byte {
	file_SceneForceUnlockNotify_proto_rawDescOnce.Do(func() {
		file_SceneForceUnlockNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneForceUnlockNotify_proto_rawDescData)
	})
	return file_SceneForceUnlockNotify_proto_rawDescData
}

var file_SceneForceUnlockNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SceneForceUnlockNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SceneForceUnlockNotify_proto_goTypes = []interface{}{
	(SceneForceUnlockNotify_CmdId)(0), // 0: proto.SceneForceUnlockNotify.CmdId
	(*SceneForceUnlockNotify)(nil),    // 1: proto.SceneForceUnlockNotify
}
var file_SceneForceUnlockNotify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SceneForceUnlockNotify_proto_init() }
func file_SceneForceUnlockNotify_proto_init() {
	if File_SceneForceUnlockNotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SceneForceUnlockNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneForceUnlockNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneForceUnlockNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneForceUnlockNotify_proto_goTypes,
		DependencyIndexes: file_SceneForceUnlockNotify_proto_depIdxs,
		EnumInfos:         file_SceneForceUnlockNotify_proto_enumTypes,
		MessageInfos:      file_SceneForceUnlockNotify_proto_msgTypes,
	}.Build()
	File_SceneForceUnlockNotify_proto = out.File
	file_SceneForceUnlockNotify_proto_rawDesc = nil
	file_SceneForceUnlockNotify_proto_goTypes = nil
	file_SceneForceUnlockNotify_proto_depIdxs = nil
}
