// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: SceneAreaWeatherNotify.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SceneAreaWeatherNotify_CmdId int32

const (
	SceneAreaWeatherNotify_NONE             SceneAreaWeatherNotify_CmdId = 0
	SceneAreaWeatherNotify_ENET_CHANNEL_ID  SceneAreaWeatherNotify_CmdId = 0
	SceneAreaWeatherNotify_ENET_IS_RELIABLE SceneAreaWeatherNotify_CmdId = 1
	SceneAreaWeatherNotify_CMD_ID           SceneAreaWeatherNotify_CmdId = 229
)

// Enum value maps for SceneAreaWeatherNotify_CmdId.
var (
	SceneAreaWeatherNotify_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:   "ENET_IS_RELIABLE",
		229: "CMD_ID",
	}
	SceneAreaWeatherNotify_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           229,
	}
)

func (x SceneAreaWeatherNotify_CmdId) Enum() *SceneAreaWeatherNotify_CmdId {
	p := new(SceneAreaWeatherNotify_CmdId)
	*p = x
	return p
}

func (x SceneAreaWeatherNotify_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SceneAreaWeatherNotify_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_SceneAreaWeatherNotify_proto_enumTypes[0].Descriptor()
}

func (SceneAreaWeatherNotify_CmdId) Type() protoreflect.EnumType {
	return &file_SceneAreaWeatherNotify_proto_enumTypes[0]
}

func (x SceneAreaWeatherNotify_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SceneAreaWeatherNotify_CmdId.Descriptor instead.
func (SceneAreaWeatherNotify_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_SceneAreaWeatherNotify_proto_rawDescGZIP(), []int{0, 0}
}

type SceneAreaWeatherNotify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeatherGadgetId uint32            `protobuf:"varint,13,opt,name=weather_gadget_id,json=weatherGadgetId,proto3" json:"weather_gadget_id,omitempty"`
	WeatherValueMap map[uint32]string `protobuf:"bytes,10,rep,name=weather_value_map,json=weatherValueMap,proto3" json:"weather_value_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	WeatherAreaId   uint32            `protobuf:"varint,15,opt,name=weather_area_id,json=weatherAreaId,proto3" json:"weather_area_id,omitempty"`
	ClimateType     uint32            `protobuf:"varint,14,opt,name=climate_type,json=climateType,proto3" json:"climate_type,omitempty"`
	TransDuration   float32           `protobuf:"fixed32,11,opt,name=trans_duration,json=transDuration,proto3" json:"trans_duration,omitempty"`
}

func (x *SceneAreaWeatherNotify) Reset() {
	*x = SceneAreaWeatherNotify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SceneAreaWeatherNotify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SceneAreaWeatherNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SceneAreaWeatherNotify) ProtoMessage() {}

func (x *SceneAreaWeatherNotify) ProtoReflect() protoreflect.Message {
	mi := &file_SceneAreaWeatherNotify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SceneAreaWeatherNotify.ProtoReflect.Descriptor instead.
func (*SceneAreaWeatherNotify) Descriptor() ([]byte, []int) {
	return file_SceneAreaWeatherNotify_proto_rawDescGZIP(), []int{0}
}

func (x *SceneAreaWeatherNotify) GetWeatherGadgetId() uint32 {
	if x != nil {
		return x.WeatherGadgetId
	}
	return 0
}

func (x *SceneAreaWeatherNotify) GetWeatherValueMap() map[uint32]string {
	if x != nil {
		return x.WeatherValueMap
	}
	return nil
}

func (x *SceneAreaWeatherNotify) GetWeatherAreaId() uint32 {
	if x != nil {
		return x.WeatherAreaId
	}
	return 0
}

func (x *SceneAreaWeatherNotify) GetClimateType() uint32 {
	if x != nil {
		return x.ClimateType
	}
	return 0
}

func (x *SceneAreaWeatherNotify) GetTransDuration() float32 {
	if x != nil {
		return x.TransDuration
	}
	return 0
}

var File_SceneAreaWeatherNotify_proto protoreflect.FileDescriptor

var file_SceneAreaWeatherNotify_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x41, 0x72, 0x65, 0x61, 0x57, 0x65, 0x61, 0x74, 0x68,
	0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x03, 0x0a, 0x16, 0x53, 0x63, 0x65, 0x6e, 0x65, 0x41,
	0x72, 0x65, 0x61, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x12, 0x2a, 0x0a, 0x11, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x64, 0x67,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x77, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12, 0x5e, 0x0a, 0x11,
	0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x6d, 0x61,
	0x70, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x63, 0x65, 0x6e, 0x65, 0x41, 0x72, 0x65, 0x61, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x2e, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0f, 0x77, 0x65, 0x61,
	0x74, 0x68, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x61, 0x70, 0x12, 0x26, 0x0a, 0x0f,
	0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x69, 0x64, 0x18,
	0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x77, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x41, 0x72,
	0x65, 0x61, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x63, 0x6c, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x5f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x42,
	0x0a, 0x14, 0x57, 0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e,
	0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xe5, 0x01, 0x1a, 0x02, 0x10,
	0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SceneAreaWeatherNotify_proto_rawDescOnce sync.Once
	file_SceneAreaWeatherNotify_proto_rawDescData = file_SceneAreaWeatherNotify_proto_rawDesc
)

func file_SceneAreaWeatherNotify_proto_rawDescGZIP() []byte {
	file_SceneAreaWeatherNotify_proto_rawDescOnce.Do(func() {
		file_SceneAreaWeatherNotify_proto_rawDescData = protoimpl.X.CompressGZIP(file_SceneAreaWeatherNotify_proto_rawDescData)
	})
	return file_SceneAreaWeatherNotify_proto_rawDescData
}

var file_SceneAreaWeatherNotify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SceneAreaWeatherNotify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_SceneAreaWeatherNotify_proto_goTypes = []interface{}{
	(SceneAreaWeatherNotify_CmdId)(0), // 0: proto.SceneAreaWeatherNotify.CmdId
	(*SceneAreaWeatherNotify)(nil),    // 1: proto.SceneAreaWeatherNotify
	nil,                               // 2: proto.SceneAreaWeatherNotify.WeatherValueMapEntry
}
var file_SceneAreaWeatherNotify_proto_depIdxs = []int32{
	2, // 0: proto.SceneAreaWeatherNotify.weather_value_map:type_name -> proto.SceneAreaWeatherNotify.WeatherValueMapEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SceneAreaWeatherNotify_proto_init() }
func file_SceneAreaWeatherNotify_proto_init() {
	if File_SceneAreaWeatherNotify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SceneAreaWeatherNotify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SceneAreaWeatherNotify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SceneAreaWeatherNotify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SceneAreaWeatherNotify_proto_goTypes,
		DependencyIndexes: file_SceneAreaWeatherNotify_proto_depIdxs,
		EnumInfos:         file_SceneAreaWeatherNotify_proto_enumTypes,
		MessageInfos:      file_SceneAreaWeatherNotify_proto_msgTypes,
	}.Build()
	File_SceneAreaWeatherNotify_proto = out.File
	file_SceneAreaWeatherNotify_proto_rawDesc = nil
	file_SceneAreaWeatherNotify_proto_goTypes = nil
	file_SceneAreaWeatherNotify_proto_depIdxs = nil
}
