// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: SetPlayerBirthdayReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetPlayerBirthdayReq_CmdId int32

const (
	SetPlayerBirthdayReq_NONE             SetPlayerBirthdayReq_CmdId = 0
	SetPlayerBirthdayReq_ENET_CHANNEL_ID  SetPlayerBirthdayReq_CmdId = 0
	SetPlayerBirthdayReq_ENET_IS_RELIABLE SetPlayerBirthdayReq_CmdId = 1
	SetPlayerBirthdayReq_IS_ALLOW_CLIENT  SetPlayerBirthdayReq_CmdId = 1
	SetPlayerBirthdayReq_CMD_ID           SetPlayerBirthdayReq_CmdId = 4007
)

// Enum value maps for SetPlayerBirthdayReq_CmdId.
var (
	SetPlayerBirthdayReq_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		4007: "CMD_ID",
	}
	SetPlayerBirthdayReq_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           4007,
	}
)

func (x SetPlayerBirthdayReq_CmdId) Enum() *SetPlayerBirthdayReq_CmdId {
	p := new(SetPlayerBirthdayReq_CmdId)
	*p = x
	return p
}

func (x SetPlayerBirthdayReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SetPlayerBirthdayReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_SetPlayerBirthdayReq_proto_enumTypes[0].Descriptor()
}

func (SetPlayerBirthdayReq_CmdId) Type() protoreflect.EnumType {
	return &file_SetPlayerBirthdayReq_proto_enumTypes[0]
}

func (x SetPlayerBirthdayReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SetPlayerBirthdayReq_CmdId.Descriptor instead.
func (SetPlayerBirthdayReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_SetPlayerBirthdayReq_proto_rawDescGZIP(), []int{0, 0}
}

type SetPlayerBirthdayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Birthday *Birthday `protobuf:"bytes,10,opt,name=birthday,proto3" json:"birthday,omitempty"`
}

func (x *SetPlayerBirthdayReq) Reset() {
	*x = SetPlayerBirthdayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SetPlayerBirthdayReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetPlayerBirthdayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPlayerBirthdayReq) ProtoMessage() {}

func (x *SetPlayerBirthdayReq) ProtoReflect() protoreflect.Message {
	mi := &file_SetPlayerBirthdayReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPlayerBirthdayReq.ProtoReflect.Descriptor instead.
func (*SetPlayerBirthdayReq) Descriptor() ([]byte, []int) {
	return file_SetPlayerBirthdayReq_proto_rawDescGZIP(), []int{0}
}

func (x *SetPlayerBirthdayReq) GetBirthday() *Birthday {
	if x != nil {
		return x.Birthday
	}
	return nil
}

var File_SetPlayerBirthdayReq_proto protoreflect.FileDescriptor

var file_SetPlayerBirthdayReq_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x69, 0x72, 0x74, 0x68,
	0x64, 0x61, 0x79, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x2b, 0x0a, 0x08,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x52,
	0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x22, 0x62, 0x0a, 0x05, 0x43, 0x6d, 0x64,
	0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c,
	0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53, 0x5f, 0x41, 0x4c,
	0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06,
	0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xa7, 0x1f, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_SetPlayerBirthdayReq_proto_rawDescOnce sync.Once
	file_SetPlayerBirthdayReq_proto_rawDescData = file_SetPlayerBirthdayReq_proto_rawDesc
)

func file_SetPlayerBirthdayReq_proto_rawDescGZIP() []byte {
	file_SetPlayerBirthdayReq_proto_rawDescOnce.Do(func() {
		file_SetPlayerBirthdayReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_SetPlayerBirthdayReq_proto_rawDescData)
	})
	return file_SetPlayerBirthdayReq_proto_rawDescData
}

var file_SetPlayerBirthdayReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_SetPlayerBirthdayReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SetPlayerBirthdayReq_proto_goTypes = []interface{}{
	(SetPlayerBirthdayReq_CmdId)(0), // 0: proto.SetPlayerBirthdayReq.CmdId
	(*SetPlayerBirthdayReq)(nil),    // 1: proto.SetPlayerBirthdayReq
	(*Birthday)(nil),                // 2: proto.Birthday
}
var file_SetPlayerBirthdayReq_proto_depIdxs = []int32{
	2, // 0: proto.SetPlayerBirthdayReq.birthday:type_name -> proto.Birthday
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_SetPlayerBirthdayReq_proto_init() }
func file_SetPlayerBirthdayReq_proto_init() {
	if File_SetPlayerBirthdayReq_proto != nil {
		return
	}
	file_Birthday_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_SetPlayerBirthdayReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetPlayerBirthdayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SetPlayerBirthdayReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SetPlayerBirthdayReq_proto_goTypes,
		DependencyIndexes: file_SetPlayerBirthdayReq_proto_depIdxs,
		EnumInfos:         file_SetPlayerBirthdayReq_proto_enumTypes,
		MessageInfos:      file_SetPlayerBirthdayReq_proto_msgTypes,
	}.Build()
	File_SetPlayerBirthdayReq_proto = out.File
	file_SetPlayerBirthdayReq_proto_rawDesc = nil
	file_SetPlayerBirthdayReq_proto_goTypes = nil
	file_SetPlayerBirthdayReq_proto_depIdxs = nil
}
