// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: TowerEnterLevelRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TowerEnterLevelRsp_CmdId int32

const (
	TowerEnterLevelRsp_NONE             TowerEnterLevelRsp_CmdId = 0
	TowerEnterLevelRsp_ENET_CHANNEL_ID  TowerEnterLevelRsp_CmdId = 0
	TowerEnterLevelRsp_ENET_IS_RELIABLE TowerEnterLevelRsp_CmdId = 1
	TowerEnterLevelRsp_CMD_ID           TowerEnterLevelRsp_CmdId = 2427
)

// Enum value maps for TowerEnterLevelRsp_CmdId.
var (
	TowerEnterLevelRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		2427: "CMD_ID",
	}
	TowerEnterLevelRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           2427,
	}
)

func (x TowerEnterLevelRsp_CmdId) Enum() *TowerEnterLevelRsp_CmdId {
	p := new(TowerEnterLevelRsp_CmdId)
	*p = x
	return p
}

func (x TowerEnterLevelRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TowerEnterLevelRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_TowerEnterLevelRsp_proto_enumTypes[0].Descriptor()
}

func (TowerEnterLevelRsp_CmdId) Type() protoreflect.EnumType {
	return &file_TowerEnterLevelRsp_proto_enumTypes[0]
}

func (x TowerEnterLevelRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TowerEnterLevelRsp_CmdId.Descriptor instead.
func (TowerEnterLevelRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_TowerEnterLevelRsp_proto_rawDescGZIP(), []int{0, 0}
}

type TowerEnterLevelRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode         int32    `protobuf:"varint,14,opt,name=retcode,proto3" json:"retcode,omitempty"`
	FloorId         uint32   `protobuf:"varint,6,opt,name=floor_id,json=floorId,proto3" json:"floor_id,omitempty"`
	LevelIndex      uint32   `protobuf:"varint,8,opt,name=level_index,json=levelIndex,proto3" json:"level_index,omitempty"`
	TowerBuffIdList []uint32 `protobuf:"varint,7,rep,packed,name=tower_buff_id_list,json=towerBuffIdList,proto3" json:"tower_buff_id_list,omitempty"`
}

func (x *TowerEnterLevelRsp) Reset() {
	*x = TowerEnterLevelRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_TowerEnterLevelRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerEnterLevelRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerEnterLevelRsp) ProtoMessage() {}

func (x *TowerEnterLevelRsp) ProtoReflect() protoreflect.Message {
	mi := &file_TowerEnterLevelRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerEnterLevelRsp.ProtoReflect.Descriptor instead.
func (*TowerEnterLevelRsp) Descriptor() ([]byte, []int) {
	return file_TowerEnterLevelRsp_proto_rawDescGZIP(), []int{0}
}

func (x *TowerEnterLevelRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *TowerEnterLevelRsp) GetFloorId() uint32 {
	if x != nil {
		return x.FloorId
	}
	return 0
}

func (x *TowerEnterLevelRsp) GetLevelIndex() uint32 {
	if x != nil {
		return x.LevelIndex
	}
	return 0
}

func (x *TowerEnterLevelRsp) GetTowerBuffIdList() []uint32 {
	if x != nil {
		return x.TowerBuffIdList
	}
	return nil
}

var File_TowerEnterLevelRsp_proto protoreflect.FileDescriptor

var file_TowerEnterLevelRsp_proto_rawDesc = []byte{
	0x0a, 0x18, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xe6, 0x01, 0x0a, 0x12, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x6c, 0x6f, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x2b,
	0x0a, 0x12, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x5f, 0x62, 0x75, 0x66, 0x66, 0x5f, 0x69, 0x64, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0f, 0x74, 0x6f, 0x77, 0x65,
	0x72, 0x42, 0x75, 0x66, 0x66, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x05, 0x43,
	0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52,
	0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44,
	0x5f, 0x49, 0x44, 0x10, 0xfb, 0x12, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_TowerEnterLevelRsp_proto_rawDescOnce sync.Once
	file_TowerEnterLevelRsp_proto_rawDescData = file_TowerEnterLevelRsp_proto_rawDesc
)

func file_TowerEnterLevelRsp_proto_rawDescGZIP() []byte {
	file_TowerEnterLevelRsp_proto_rawDescOnce.Do(func() {
		file_TowerEnterLevelRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_TowerEnterLevelRsp_proto_rawDescData)
	})
	return file_TowerEnterLevelRsp_proto_rawDescData
}

var file_TowerEnterLevelRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TowerEnterLevelRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_TowerEnterLevelRsp_proto_goTypes = []interface{}{
	(TowerEnterLevelRsp_CmdId)(0), // 0: proto.TowerEnterLevelRsp.CmdId
	(*TowerEnterLevelRsp)(nil),    // 1: proto.TowerEnterLevelRsp
}
var file_TowerEnterLevelRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_TowerEnterLevelRsp_proto_init() }
func file_TowerEnterLevelRsp_proto_init() {
	if File_TowerEnterLevelRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_TowerEnterLevelRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerEnterLevelRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_TowerEnterLevelRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TowerEnterLevelRsp_proto_goTypes,
		DependencyIndexes: file_TowerEnterLevelRsp_proto_depIdxs,
		EnumInfos:         file_TowerEnterLevelRsp_proto_enumTypes,
		MessageInfos:      file_TowerEnterLevelRsp_proto_msgTypes,
	}.Build()
	File_TowerEnterLevelRsp_proto = out.File
	file_TowerEnterLevelRsp_proto_rawDesc = nil
	file_TowerEnterLevelRsp_proto_goTypes = nil
	file_TowerEnterLevelRsp_proto_depIdxs = nil
}
