// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: UnlockAvatarTalentReq.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnlockAvatarTalentReq_CmdId int32

const (
	UnlockAvatarTalentReq_ENET_CHANNEL_ID  UnlockAvatarTalentReq_CmdId = 0
	UnlockAvatarTalentReq_NONE             UnlockAvatarTalentReq_CmdId = 0
	UnlockAvatarTalentReq_ENET_IS_RELIABLE UnlockAvatarTalentReq_CmdId = 1
	UnlockAvatarTalentReq_IS_ALLOW_CLIENT  UnlockAvatarTalentReq_CmdId = 1
	UnlockAvatarTalentReq_CMD_ID           UnlockAvatarTalentReq_CmdId = 1049
)

// Enum value maps for UnlockAvatarTalentReq_CmdId.
var (
	UnlockAvatarTalentReq_CmdId_name = map[int32]string{
		0: "ENET_CHANNEL_ID",
		// Duplicate value: 0: "NONE",
		1: "ENET_IS_RELIABLE",
		// Duplicate value: 1: "IS_ALLOW_CLIENT",
		1049: "CMD_ID",
	}
	UnlockAvatarTalentReq_CmdId_value = map[string]int32{
		"ENET_CHANNEL_ID":  0,
		"NONE":             0,
		"ENET_IS_RELIABLE": 1,
		"IS_ALLOW_CLIENT":  1,
		"CMD_ID":           1049,
	}
)

func (x UnlockAvatarTalentReq_CmdId) Enum() *UnlockAvatarTalentReq_CmdId {
	p := new(UnlockAvatarTalentReq_CmdId)
	*p = x
	return p
}

func (x UnlockAvatarTalentReq_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UnlockAvatarTalentReq_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_UnlockAvatarTalentReq_proto_enumTypes[0].Descriptor()
}

func (UnlockAvatarTalentReq_CmdId) Type() protoreflect.EnumType {
	return &file_UnlockAvatarTalentReq_proto_enumTypes[0]
}

func (x UnlockAvatarTalentReq_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UnlockAvatarTalentReq_CmdId.Descriptor instead.
func (UnlockAvatarTalentReq_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_UnlockAvatarTalentReq_proto_rawDescGZIP(), []int{0, 0}
}

type UnlockAvatarTalentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarGuid uint64 `protobuf:"varint,1,opt,name=avatar_guid,json=avatarGuid,proto3" json:"avatar_guid,omitempty"`
	TalentId   uint32 `protobuf:"varint,2,opt,name=talent_id,json=talentId,proto3" json:"talent_id,omitempty"`
}

func (x *UnlockAvatarTalentReq) Reset() {
	*x = UnlockAvatarTalentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UnlockAvatarTalentReq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockAvatarTalentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockAvatarTalentReq) ProtoMessage() {}

func (x *UnlockAvatarTalentReq) ProtoReflect() protoreflect.Message {
	mi := &file_UnlockAvatarTalentReq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockAvatarTalentReq.ProtoReflect.Descriptor instead.
func (*UnlockAvatarTalentReq) Descriptor() ([]byte, []int) {
	return file_UnlockAvatarTalentReq_proto_rawDescGZIP(), []int{0}
}

func (x *UnlockAvatarTalentReq) GetAvatarGuid() uint64 {
	if x != nil {
		return x.AvatarGuid
	}
	return 0
}

func (x *UnlockAvatarTalentReq) GetTalentId() uint32 {
	if x != nil {
		return x.TalentId
	}
	return 0
}

var File_UnlockAvatarTalentReq_proto protoreflect.FileDescriptor

var file_UnlockAvatarTalentReq_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x54, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb9, 0x01, 0x0a, 0x15, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x47, 0x75, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x05,
	0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48,
	0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f,
	0x4e, 0x45, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f,
	0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x53,
	0x5f, 0x41, 0x4c, 0x4c, 0x4f, 0x57, 0x5f, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x99, 0x08, 0x1a, 0x02, 0x10, 0x01,
	0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_UnlockAvatarTalentReq_proto_rawDescOnce sync.Once
	file_UnlockAvatarTalentReq_proto_rawDescData = file_UnlockAvatarTalentReq_proto_rawDesc
)

func file_UnlockAvatarTalentReq_proto_rawDescGZIP() []byte {
	file_UnlockAvatarTalentReq_proto_rawDescOnce.Do(func() {
		file_UnlockAvatarTalentReq_proto_rawDescData = protoimpl.X.CompressGZIP(file_UnlockAvatarTalentReq_proto_rawDescData)
	})
	return file_UnlockAvatarTalentReq_proto_rawDescData
}

var file_UnlockAvatarTalentReq_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_UnlockAvatarTalentReq_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_UnlockAvatarTalentReq_proto_goTypes = []interface{}{
	(UnlockAvatarTalentReq_CmdId)(0), // 0: proto.UnlockAvatarTalentReq.CmdId
	(*UnlockAvatarTalentReq)(nil),    // 1: proto.UnlockAvatarTalentReq
}
var file_UnlockAvatarTalentReq_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_UnlockAvatarTalentReq_proto_init() }
func file_UnlockAvatarTalentReq_proto_init() {
	if File_UnlockAvatarTalentReq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_UnlockAvatarTalentReq_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockAvatarTalentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UnlockAvatarTalentReq_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UnlockAvatarTalentReq_proto_goTypes,
		DependencyIndexes: file_UnlockAvatarTalentReq_proto_depIdxs,
		EnumInfos:         file_UnlockAvatarTalentReq_proto_enumTypes,
		MessageInfos:      file_UnlockAvatarTalentReq_proto_msgTypes,
	}.Build()
	File_UnlockAvatarTalentReq_proto = out.File
	file_UnlockAvatarTalentReq_proto_rawDesc = nil
	file_UnlockAvatarTalentReq_proto_goTypes = nil
	file_UnlockAvatarTalentReq_proto_depIdxs = nil
}
