// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: UseWidgetCreateGadgetRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UseWidgetCreateGadgetRsp_CmdId int32

const (
	UseWidgetCreateGadgetRsp_NONE             UseWidgetCreateGadgetRsp_CmdId = 0
	UseWidgetCreateGadgetRsp_ENET_CHANNEL_ID  UseWidgetCreateGadgetRsp_CmdId = 0
	UseWidgetCreateGadgetRsp_ENET_IS_RELIABLE UseWidgetCreateGadgetRsp_CmdId = 1
	UseWidgetCreateGadgetRsp_CMD_ID           UseWidgetCreateGadgetRsp_CmdId = 4283
)

// Enum value maps for UseWidgetCreateGadgetRsp_CmdId.
var (
	UseWidgetCreateGadgetRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:    "ENET_IS_RELIABLE",
		4283: "CMD_ID",
	}
	UseWidgetCreateGadgetRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           4283,
	}
)

func (x UseWidgetCreateGadgetRsp_CmdId) Enum() *UseWidgetCreateGadgetRsp_CmdId {
	p := new(UseWidgetCreateGadgetRsp_CmdId)
	*p = x
	return p
}

func (x UseWidgetCreateGadgetRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UseWidgetCreateGadgetRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_UseWidgetCreateGadgetRsp_proto_enumTypes[0].Descriptor()
}

func (UseWidgetCreateGadgetRsp_CmdId) Type() protoreflect.EnumType {
	return &file_UseWidgetCreateGadgetRsp_proto_enumTypes[0]
}

func (x UseWidgetCreateGadgetRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UseWidgetCreateGadgetRsp_CmdId.Descriptor instead.
func (UseWidgetCreateGadgetRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_UseWidgetCreateGadgetRsp_proto_rawDescGZIP(), []int{0, 0}
}

type UseWidgetCreateGadgetRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode    int32  `protobuf:"varint,13,opt,name=retcode,proto3" json:"retcode,omitempty"`
	MaterialId uint32 `protobuf:"varint,2,opt,name=material_id,json=materialId,proto3" json:"material_id,omitempty"`
}

func (x *UseWidgetCreateGadgetRsp) Reset() {
	*x = UseWidgetCreateGadgetRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_UseWidgetCreateGadgetRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UseWidgetCreateGadgetRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseWidgetCreateGadgetRsp) ProtoMessage() {}

func (x *UseWidgetCreateGadgetRsp) ProtoReflect() protoreflect.Message {
	mi := &file_UseWidgetCreateGadgetRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseWidgetCreateGadgetRsp.ProtoReflect.Descriptor instead.
func (*UseWidgetCreateGadgetRsp) Descriptor() ([]byte, []int) {
	return file_UseWidgetCreateGadgetRsp_proto_rawDescGZIP(), []int{0}
}

func (x *UseWidgetCreateGadgetRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *UseWidgetCreateGadgetRsp) GetMaterialId() uint32 {
	if x != nil {
		return x.MaterialId
	}
	return 0
}

var File_UseWidgetCreateGadgetRsp_proto protoreflect.FileDescriptor

var file_UseWidgetCreateGadgetRsp_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x55, 0x73, 0x65, 0x57, 0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x52, 0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa4, 0x01, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x57,
	0x69, 0x64, 0x67, 0x65, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x61, 0x64, 0x67, 0x65,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x64, 0x22,
	0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45,
	0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e, 0x4e,
	0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x4e, 0x45, 0x54, 0x5f,
	0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0b, 0x0a,
	0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xbb, 0x21, 0x1a, 0x02, 0x10, 0x01, 0x42, 0x0a,
	0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_UseWidgetCreateGadgetRsp_proto_rawDescOnce sync.Once
	file_UseWidgetCreateGadgetRsp_proto_rawDescData = file_UseWidgetCreateGadgetRsp_proto_rawDesc
)

func file_UseWidgetCreateGadgetRsp_proto_rawDescGZIP() []byte {
	file_UseWidgetCreateGadgetRsp_proto_rawDescOnce.Do(func() {
		file_UseWidgetCreateGadgetRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_UseWidgetCreateGadgetRsp_proto_rawDescData)
	})
	return file_UseWidgetCreateGadgetRsp_proto_rawDescData
}

var file_UseWidgetCreateGadgetRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_UseWidgetCreateGadgetRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_UseWidgetCreateGadgetRsp_proto_goTypes = []interface{}{
	(UseWidgetCreateGadgetRsp_CmdId)(0), // 0: proto.UseWidgetCreateGadgetRsp.CmdId
	(*UseWidgetCreateGadgetRsp)(nil),    // 1: proto.UseWidgetCreateGadgetRsp
}
var file_UseWidgetCreateGadgetRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_UseWidgetCreateGadgetRsp_proto_init() }
func file_UseWidgetCreateGadgetRsp_proto_init() {
	if File_UseWidgetCreateGadgetRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_UseWidgetCreateGadgetRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UseWidgetCreateGadgetRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_UseWidgetCreateGadgetRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_UseWidgetCreateGadgetRsp_proto_goTypes,
		DependencyIndexes: file_UseWidgetCreateGadgetRsp_proto_depIdxs,
		EnumInfos:         file_UseWidgetCreateGadgetRsp_proto_enumTypes,
		MessageInfos:      file_UseWidgetCreateGadgetRsp_proto_msgTypes,
	}.Build()
	File_UseWidgetCreateGadgetRsp_proto = out.File
	file_UseWidgetCreateGadgetRsp_proto_rawDesc = nil
	file_UseWidgetCreateGadgetRsp_proto_goTypes = nil
	file_UseWidgetCreateGadgetRsp_proto_depIdxs = nil
}
