// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.7.0
// source: WeaponPromoteRsp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeaponPromoteRsp_CmdId int32

const (
	WeaponPromoteRsp_NONE             WeaponPromoteRsp_CmdId = 0
	WeaponPromoteRsp_ENET_CHANNEL_ID  WeaponPromoteRsp_CmdId = 0
	WeaponPromoteRsp_ENET_IS_RELIABLE WeaponPromoteRsp_CmdId = 1
	WeaponPromoteRsp_CMD_ID           WeaponPromoteRsp_CmdId = 606
)

// Enum value maps for WeaponPromoteRsp_CmdId.
var (
	WeaponPromoteRsp_CmdId_name = map[int32]string{
		0: "NONE",
		// Duplicate value: 0: "ENET_CHANNEL_ID",
		1:   "ENET_IS_RELIABLE",
		606: "CMD_ID",
	}
	WeaponPromoteRsp_CmdId_value = map[string]int32{
		"NONE":             0,
		"ENET_CHANNEL_ID":  0,
		"ENET_IS_RELIABLE": 1,
		"CMD_ID":           606,
	}
)

func (x WeaponPromoteRsp_CmdId) Enum() *WeaponPromoteRsp_CmdId {
	p := new(WeaponPromoteRsp_CmdId)
	*p = x
	return p
}

func (x WeaponPromoteRsp_CmdId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeaponPromoteRsp_CmdId) Descriptor() protoreflect.EnumDescriptor {
	return file_WeaponPromoteRsp_proto_enumTypes[0].Descriptor()
}

func (WeaponPromoteRsp_CmdId) Type() protoreflect.EnumType {
	return &file_WeaponPromoteRsp_proto_enumTypes[0]
}

func (x WeaponPromoteRsp_CmdId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeaponPromoteRsp_CmdId.Descriptor instead.
func (WeaponPromoteRsp_CmdId) EnumDescriptor() ([]byte, []int) {
	return file_WeaponPromoteRsp_proto_rawDescGZIP(), []int{0, 0}
}

type WeaponPromoteRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Retcode          int32  `protobuf:"varint,1,opt,name=retcode,proto3" json:"retcode,omitempty"`
	TargetWeaponGuid uint64 `protobuf:"varint,2,opt,name=target_weapon_guid,json=targetWeaponGuid,proto3" json:"target_weapon_guid,omitempty"`
	OldPromoteLevel  uint32 `protobuf:"varint,3,opt,name=old_promote_level,json=oldPromoteLevel,proto3" json:"old_promote_level,omitempty"`
	CurPromoteLevel  uint32 `protobuf:"varint,4,opt,name=cur_promote_level,json=curPromoteLevel,proto3" json:"cur_promote_level,omitempty"`
}

func (x *WeaponPromoteRsp) Reset() {
	*x = WeaponPromoteRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_WeaponPromoteRsp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeaponPromoteRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponPromoteRsp) ProtoMessage() {}

func (x *WeaponPromoteRsp) ProtoReflect() protoreflect.Message {
	mi := &file_WeaponPromoteRsp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponPromoteRsp.ProtoReflect.Descriptor instead.
func (*WeaponPromoteRsp) Descriptor() ([]byte, []int) {
	return file_WeaponPromoteRsp_proto_rawDescGZIP(), []int{0}
}

func (x *WeaponPromoteRsp) GetRetcode() int32 {
	if x != nil {
		return x.Retcode
	}
	return 0
}

func (x *WeaponPromoteRsp) GetTargetWeaponGuid() uint64 {
	if x != nil {
		return x.TargetWeaponGuid
	}
	return 0
}

func (x *WeaponPromoteRsp) GetOldPromoteLevel() uint32 {
	if x != nil {
		return x.OldPromoteLevel
	}
	return 0
}

func (x *WeaponPromoteRsp) GetCurPromoteLevel() uint32 {
	if x != nil {
		return x.CurPromoteLevel
	}
	return 0
}

var File_WeaponPromoteRsp_proto protoreflect.FileDescriptor

var file_WeaponPromoteRsp_proto_rawDesc = []byte{
	0x0a, 0x16, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x52,
	0x73, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x81, 0x02, 0x0a, 0x10, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x65, 0x52, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2c,
	0x0a, 0x12, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x5f,
	0x67, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x10, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x47, 0x75, 0x69, 0x64, 0x12, 0x2a, 0x0a, 0x11,
	0x6f, 0x6c, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6f, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x6d,
	0x6f, 0x74, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2a, 0x0a, 0x11, 0x63, 0x75, 0x72, 0x5f,
	0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x63, 0x75, 0x72, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x4d, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x64, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x45, 0x54, 0x5f,
	0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45, 0x4c, 0x5f, 0x49, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10,
	0x45, 0x4e, 0x45, 0x54, 0x5f, 0x49, 0x53, 0x5f, 0x52, 0x45, 0x4c, 0x49, 0x41, 0x42, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x06, 0x43, 0x4d, 0x44, 0x5f, 0x49, 0x44, 0x10, 0xde, 0x04, 0x1a,
	0x02, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_WeaponPromoteRsp_proto_rawDescOnce sync.Once
	file_WeaponPromoteRsp_proto_rawDescData = file_WeaponPromoteRsp_proto_rawDesc
)

func file_WeaponPromoteRsp_proto_rawDescGZIP() []byte {
	file_WeaponPromoteRsp_proto_rawDescOnce.Do(func() {
		file_WeaponPromoteRsp_proto_rawDescData = protoimpl.X.CompressGZIP(file_WeaponPromoteRsp_proto_rawDescData)
	})
	return file_WeaponPromoteRsp_proto_rawDescData
}

var file_WeaponPromoteRsp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_WeaponPromoteRsp_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_WeaponPromoteRsp_proto_goTypes = []interface{}{
	(WeaponPromoteRsp_CmdId)(0), // 0: proto.WeaponPromoteRsp.CmdId
	(*WeaponPromoteRsp)(nil),    // 1: proto.WeaponPromoteRsp
}
var file_WeaponPromoteRsp_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_WeaponPromoteRsp_proto_init() }
func file_WeaponPromoteRsp_proto_init() {
	if File_WeaponPromoteRsp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_WeaponPromoteRsp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeaponPromoteRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_WeaponPromoteRsp_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_WeaponPromoteRsp_proto_goTypes,
		DependencyIndexes: file_WeaponPromoteRsp_proto_depIdxs,
		EnumInfos:         file_WeaponPromoteRsp_proto_enumTypes,
		MessageInfos:      file_WeaponPromoteRsp_proto_msgTypes,
	}.Build()
	File_WeaponPromoteRsp_proto = out.File
	file_WeaponPromoteRsp_proto_rawDesc = nil
	file_WeaponPromoteRsp_proto_goTypes = nil
	file_WeaponPromoteRsp_proto_depIdxs = nil
}
